services:
  backend:
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - xploitcraft_network
    restart: always
    depends_on:
      - redis

  frontend:
    container_name: frontend_service
    build:
      context: ./frontend/my-react-app
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - xploitcraft_network
    restart: always

  mongodb:
    container_name: mongodb_service
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - xploitcraft_network
    restart: unless-stopped

  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - xploitcraft_network
    restart: unless-stopped

  apache:
    container_name: apache_service
    build:
      context: ./apache
      dockerfile: Dockerfile.apache
    ports:
      - "8080:8080"
    networks:
      - xploitcraft_network
    volumes:
     - ./apache/apache_server.conf:/usr/local/apache2/conf/extra/apache_server.conf
     - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always
    
  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf          
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - xploitcraft_network
    depends_on:
      - apache
    restart: unless-stopped

networks:
  xploitcraft_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local






