export const ATTACK_TYPES = [
    "AI Activation Exploit",
  "AI Algorithm Manipulation",
  "AI Data Leakage",
  "AI Data Leakage Exploit",
  "AI Decision Exploit",
  "AI Gradient Exploit",
  "AI Hyperparameter Exploit",
  "AI Inference Attack",
  "AI Loss Function Exploit",
  "AI Model Adversarial Example",
  "AI Model Extraction",
  "AI Model Inversion Attack",
  "AI Model Membership Inference",
  "AI Model Membership Inference Attack",
  "AI Model Poisoning",
  "AI Model Reverse Engineering",
  "AI Output Manipulation",
  "AI System Hijacking",
  "AI Training Data Poisoning",
  "AI Weight Manipulation",
  "AI-Controlled Traffic Light Exploit",
  "AI-Driven Spear Phishing",
  "AI-Generated Fake User Exploit",
  "AI-Powered Phishing Attack",
  "AI-Powered Spear Phishing",
  "API Abuse",
  "API Credential Theft",
  "API Injection",
  "ARP Poisoning",
  "ARP Spoofing",
  "Acoustic Side-Channel",
  "Admin Share Access",
  "Advanced Blockchain Exploit",
  "Advanced Persistent Threat (APT)",
  "Advanced Ransomware Variant",
  "Adversarial AI Attack",
  "Adversarial Machine Learning Attack",
  "Adware",
  "Adware Injection",
  "Affiliate Fraud",
  "Air Gap Attack",
  "Amplification Attack",
  "Application Layer DDoS",
  "Astroturfing",
  "Augmented Reality (AR) Device Exploit",
  "Automated Malware Generation",
  "Automated Teller Machine (ATM) Malware",
  "Automotive System Attack",
  "Autonomous Drone Malware",
  "Autonomous Vehicle Malware",
  "BEAST Attack",
  "BGP Hijacking",
  "BREACH Attack",
  "Backdoor",
  "Baiting",
  "Beacon Flooding",
  "Binary Planting",
  "Blockchain 51% Attack",
  "Blockchain Consensus Manipulation",
  "Blockchain Data Corruption",
  "Blockchain Data Poisoning",
  "Blockchain Double Spend",
  "Blockchain Fork Attack",
  "Blockchain Governance Attack",
  "Blockchain Hard Fork Exploit",
  "Blockchain Node Exploit",
  "Blockchain Node Hijacking",
  "Blockchain Privacy Leak",
  "Blockchain Relay Attack",
  "Blockchain Sidechain Exploit",
  "Blockchain Soft Fork Exploit",
  "Blockchain Storage Exploit",
  "Blockchain Timestamp Exploit",
  "Blockchain Transaction Ordering Attack",
  "Blockchain Upgrade Exploit",
  "Bluetooth Exploitation",
  "Bluetooth Jamming",
  "Bootkit Infection",
  "Border Gateway Protocol (BGP) Attack",
  "Border Gateway Protocol (BGP) Hijack",
  "Botnet",
  "Botnet Command and Control",
  "Botnet DDoS",
  "Branch Prediction Attack",
  "Brandjacking",
  "Broken Access Control",
  "Broken Authentication",
  "Brute Force Attack",
  "Buffer Overflow",
  "Buffer Overflow Exploit",
  "Business Email Compromise (BEC)",
  "Business Logic Attack",
  "CLDAP Amplification",
  "CRIME Attack",
  "CRLF Injection",
  "Cache Timing Attack",
  "Chargen Amplification",
  "Click Fraud",
  "Clickjacking",
  "Cloud API Hijacking",
  "Cloud Data Breach",
  "Cloud Infrastructure Exploit",
  "Cloud Instance Metadata Exploit",
  "Cloud Storage Bucket Enumeration",
  "Cloud Storage Bucket Enumeration Attack",
  "Cloud-Based Denial of Service",
  "Code Injection",
  "Code Reuse Attack",
  "Cold Boot Attack",
  "Command Injection",
  "Conference Room System Exploit",
  "Connected Car Exploit",
  "Connected Medical Equipment Malware",
  "Connected Public Transport Exploit",
  "Connection Flood",
  "Container Exploitation",
  "Content Spoofing",
  "Covering Tracks",
  "Credential Dumping",
  "Credential Harvesting",
  "Credential Stuffing",
  "Cross-Blockchain Attack",
  "Cross-Blockchain Sybil Attack",
  "Cross-Origin Resource Sharing (CORS) Misconfiguration",
  "Cross-Platform Credential Theft",
  "Cross-Site Request Forgery (CSRF)",
  "Cross-Site Scripting (XSS)",
  "Crypto Lending Platform Exploit",
  "Crypto Miner",
  "Crypto Staking Exploit",
  "Crypto Wallet Hijacking",
  "Crypto Yield Farming Exploit",
  "Cryptocurrency Exchange Malware",
  "Cryptojacking",
  "DApp Smart Contract Upgrade Exploit",
  "DDoS",
  "DLL Hijacking",
  "DNS Amplification",
  "DNS Amplification Attack",
  "DNS Cache Poisoning",
  "DNS Rebinding",
  "DNS Spoofing",
  "DNS Tunneling",
  "DROWN Attack",
  "Data Accessibility Exploit in Web Applications",
  "Data Annotation Exploit for AI Bias Injection",
  "Data Anonymization Exploit for Re-identification",
  "Data Archiving Exploit for Long-Term Theft",
  "Data Authenticity Exploit in Trust Systems",
  "Data Availability Exploit through DDoS Attacks",
  "Data Backup Exploit through Unauthorized Access",
  "Data Breach",
  "Data Business Continuity Exploit in Critical Systems",
  "Data Classification Exploit for Sensitive Data Access",
  "Data Compliance Exploit via Regulation Ignorance",
  "Data Confidentiality Exploit via Unauthorized Access",
  "Data Consensus Exploit in Blockchain Networks",
  "Data Consistency Exploit in Distributed Databases",
  "Data Context Exploit in Context-Aware Systems",
  "Data Decryption Exploit through Weak Keys",
  "Data Destruction Exploit via Physical Damage",
  "Data Disaster Recovery Exploit in Backup Systems",
  "Data Disposal Exploit through Incomplete Deletion",
  "Data Encryption Exploit in Transport Layer",
  "Data Exfiltration",
  "Data Exfiltration via Covert Channels",
  "Data Fabric Tampering",
  "Data Fault Tolerance Exploit in Resilient Systems",
  "Data Filtering Exploit to Remove Critical Data",
  "Data Freshness Exploit in Real-Time Systems",
  "Data Generation Exploit for AI Model Training",
  "Data Governance Exploit through Policy Bypass",
  "Data Granularity Exploit in Detailed Data Analysis",
  "Data Hashing Exploit for Integrity Bypass",
  "Data High Availability Exploit in Redundant Systems",
  "Data Incident Response Exploit in Security Protocols",
  "Data Indexing Exploit for Quick Access Abuse",
  "Data Injection in User Input Fields",
  "Data Integrity Exploit in Transaction Logs",
  "Data Intent Exploit in User Interaction Systems",
  "Data Interoperability Exploit in Cross-System Integration",
  "Data Knowledge Graph Exploit for Information Theft",
  "Data Labeling Exploit for Data Misclassification",
  "Data Leakage",
  "Data Leakage via Unsecured APIs",
  "Data Load Balancing Exploit in Server Networks",
  "Data Manipulation Attack",
  "Data Manipulation in Supply Chain Data",
  "Data Masking Exploit to Reveal Sensitive Data",
  "Data Meaning Exploit in Semantic Analysis",
  "Data Obfuscation Exploit for Code Analysis",
  "Data Ontology Exploit in Knowledge Graphs",
  "Data Partitioning Exploit for Isolated Access",
  "Data Poisoning in Machine Learning Models",
  "Data Portability Exploit in Data Migration",
  "Data Pragmatics Exploit in Communication Protocols",
  "Data Privacy Exploit through Unauthorized Sharing",
  "Data Pseudonymization Exploit for Data Linkage",
  "Data Recovery Exploit after Deletion",
  "Data Reliability Exploit in Faulty Systems",
  "Data Remanence Attack",
  "Data Replication Exploit in Redundant Systems",
  "Data Retention Exploit through Extended Storage",
  "Data Risk Assessment Exploit in Security Planning",
  "Data Sampling Exploit for Data Set Biasing",
  "Data Schema Exploit for Database Corruption",
  "Data Security Alerting Exploit through False Positives",
  "Data Security Audit Exploit through Incomplete Auditing",
  "Data Security Breach Exploit through Unauthorized Access",
  "Data Security Compliance Exploit through Non-Compliance",
  "Data Security Control Exploit through Control Bypass",
  "Data Security Detection Exploit through Detection Evasion",
  "Data Security Framework Exploit in Implementation Gaps",
  "Data Security Incident Exploit through Rapid Response",
  "Data Security Mitigation Exploit through Ineffective Measures",
  "Data Security Monitoring Exploit through Evasion Techniques",
  "Data Security Policy Exploit through Policy Violation",
  "Data Security Prevention Exploit through Proactive Measures Bypass",
  "Data Security Response Exploit through Response Delay",
  "Data Security Standard Exploit through Compliance Loopholes",
  "Data Segregation Exploit in Multi-Tenant Systems",
  "Data Semantics Exploit in Natural Language Processing",
  "Data Sharding Exploit in Distributed Systems",
  "Data Sorting Exploit in Search Algorithms",
  "Data Structure Exploit for Memory Corruption",
  "Data Synchronization Exploit in Real-Time Applications",
  "Data Syntax Exploit in Code Parsing",
  "Data Synthesis Exploit to Generate Fake Data",
  "Data Tagging Exploit for Data Sorting Bypass",
  "Data Tampering in Financial Transactions",
  "Data Taxonomy Exploit in Content Management",
  "Data Theft through Insider Threats",
  "Data Threat Intelligence Exploit in Information Sharing",
  "Data Tokenization Exploit in Payment Systems",
  "Data Usability Exploit in User Interface Design",
  "Data Validity Exploit in Data Validation Processes",
  "DeFi Automated Market Maker (AMM) Exploit",
  "DeFi Automated Market Maker Exploit",
  "DeFi Borrowing Exploit",
  "DeFi Collateral Liquidation Exploit",
  "DeFi Collateral Management Exploit",
  "DeFi Contract Upgrade Exploit",
  "DeFi Contract Upgrade Malfunction",
  "DeFi Cross-Chain Bridge Exploit",
  "DeFi Cross-Protocol Exploit",
  "DeFi Debt Ceiling Exploit",
  "DeFi Debt Position Exploit",
  "DeFi Decentralized Exchange (DEX) Exploit",
  "DeFi Farming Pool Exploit",
  "DeFi Flash Loan Arbitrage",
  "DeFi Flash Loan Arbitrage Attack",
  "DeFi Flash Loan Exploit",
  "DeFi Flash Loan Governance Attack",
  "DeFi Flash Loan Liquidation Attack",
  "DeFi Flash Loan Reentrancy Attack",
  "DeFi Flash Loan Routing Attack",
  "DeFi Front-Running Attack",
  "DeFi Futures Contract Exploit",
  "DeFi Governance Attack",
  "DeFi Governance Contract Exploit",
  "DeFi Governance Delegation Attack",
  "DeFi Governance Delegation Exploit",
  "DeFi Governance Exploit",
  "DeFi Governance Proposal Exploit",
  "DeFi Governance Token Airdrop Exploit",
  "DeFi Governance Token Allocation Exploit",
  "DeFi Governance Token Balance Manipulation",
  "DeFi Governance Token Bridge Exploit",
  "DeFi Governance Token Burn",
  "DeFi Governance Token Cross-Chain Exploit",
  "DeFi Governance Token Distribution Exploit",
  "DeFi Governance Token Distribution Manipulation",
  "DeFi Governance Token Exploit",
  "DeFi Governance Token Exploitation",
  "DeFi Governance Token Farming Exploit",
  "DeFi Governance Token Front-Running",
  "DeFi Governance Token Harvest Exploit",
  "DeFi Governance Token Lock Exploit",
  "DeFi Governance Token Lockup Exploit",
  "DeFi Governance Token Mining Exploit",
  "DeFi Governance Token Mint",
  "DeFi Governance Token Pool Exploit",
  "DeFi Governance Token Proxy Exploit",
  "DeFi Governance Token Reassignment",
  "DeFi Governance Token Sale Exploit",
  "DeFi Governance Token Swap",
  "DeFi Governance Token Swap Exploit",
  "DeFi Governance Token Theft",
  "DeFi Governance Token Transfer Exploit",
  "DeFi Governance Token Upgrade Exploit",
  "DeFi Governance Voting Exploit",
  "DeFi Insurance Pool Exploit",
  "DeFi Layer 1 Exploit",
  "DeFi Layer 2 Exploit",
  "DeFi Layer 3 Exploit",
  "DeFi Lending Protocol Exploit",
  "DeFi Liquidation Queue Manipulation",
  "DeFi Liquidity Incentive Exploit",
  "DeFi Liquidity Mining Exploit",
  "DeFi Liquidity Mining Pool Exploit",
  "DeFi Liquidity Pool Arbitrage Exploit",
  "DeFi Liquidity Pool Drain",
  "DeFi Liquidity Pool Exploit",
  "DeFi Liquidity Pool Manipulation",
  "DeFi Liquidity Pool Snapshot Attack",
  "DeFi Liquidity Provider Exploit",
  "DeFi Margin Trading Exploit",
  "DeFi Multi-Chain Exploit",
  "DeFi Options Contract Exploit",
  "DeFi Oracle Bypass",
  "DeFi Oracle Exploit",
  "DeFi Oracle Manipulation",
  "DeFi Oracle Price Manipulation",
  "DeFi Order Book Manipulation",
  "DeFi Pair Exploit",
  "DeFi Perpetual Swap Exploit",
  "DeFi Plasma Exploit",
  "DeFi Pool Rebalancing Attack",
  "DeFi Portfolio Manager Exploit",
  "DeFi Prediction Market Manipulation",
  "DeFi Price Feed Exploit",
  "DeFi Protocol Downgrade Exploit",
  "DeFi Protocol Reconfiguration Exploit",
  "DeFi Protocol Upgrade Exploit",
  "DeFi Reentrancy Attack",
  "DeFi Rollup Exploit",
  "DeFi Router Exploit",
  "DeFi Sandwich Attack",
  "DeFi Sidechain Exploit",
  "DeFi Smart Contract Exploit",
  "DeFi Smart Contract Freeze",
  "DeFi Smart Contract Reentrancy Attack",
  "DeFi Staking Contract Exploit",
  "DeFi Staking Pool Exploit",
  "DeFi Staking Pool Manipulation",
  "DeFi State Channel Exploit",
  "DeFi Strategy Exploit",
  "DeFi Synthetic Asset Exploit",
  "DeFi Synthetic Asset Manipulation",
  "DeFi Token Airdrop Exploit",
  "DeFi Token Approval Exploit",
  "DeFi Token Burn Exploit",
  "DeFi Token Burning Exploit",
  "DeFi Token Delegation Exploit",
  "DeFi Token Delisting Exploit",
  "DeFi Token Distribution Exploit",
  "DeFi Token Distribution Manipulation",
  "DeFi Token Economics Exploit",
  "DeFi Token Holder Access Exploit",
  "DeFi Token Holder Credential Exploit",
  "DeFi Token Holder Data Leakage Exploit",
  "DeFi Token Holder Enumeration Exploit",
  "DeFi Token Holder Exploit",
  "DeFi Token Holder Identity Exploit",
  "DeFi Token Holder Listing Exploit",
  "DeFi Token Holder Session Exploit",
  "DeFi Token Holder Session Hijacking",
  "DeFi Token Holder Token Approve Exploit",
  "DeFi Token Holder Token Back-Running Exploit",
  "DeFi Token Holder Token Baiting Exploit",
  "DeFi Token Holder Token Bridging Exploit",
  "DeFi Token Holder Token Burn Exploit",
  "DeFi Token Holder Token Conversion Exploit",
  "DeFi Token Holder Token Credential Dumping Exploit",
  "DeFi Token Holder Token Data Breach Exploit",
  "DeFi Token Holder Token Data Leakage Exploit",
  "DeFi Token Holder Token Decrease Allowance Exploit",
  "DeFi Token Holder Token Dusting Attack Exploit",
  "DeFi Token Holder Token Fabrication",
  "DeFi Token Holder Token Forgery",
  "DeFi Token Holder Token Front-Running Exploit",
  "DeFi Token Holder Token Gasless Transaction Exploit",
  "DeFi Token Holder Token Griefing Attack Exploit",
  "DeFi Token Holder Token Hold Exploit",
  "DeFi Token Holder Token Increase Allowance Exploit",
  "DeFi Token Holder Token Injection",
  "DeFi Token Holder Token Insider Threat Exploit",
  "DeFi Token Holder Token Lock Exploit",
  "DeFi Token Holder Token Manipulation",
  "DeFi Token Holder Token Meta-Transaction Exploit",
  "DeFi Token Holder Token Mint Exploit",
  "DeFi Token Holder Token Permit Exploit",
  "DeFi Token Holder Token Phishing Exploit",
  "DeFi Token Holder Token Prediction",
  "DeFi Token Holder Token Pretexting Exploit",
  "DeFi Token Holder Token Quid Pro Quo Exploit",
  "DeFi Token Holder Token Receive Exploit",
  "DeFi Token Holder Token Relay Exploit",
  "DeFi Token Holder Token Replay",
  "DeFi Token Holder Token Replay Exploit",
  "DeFi Token Holder Token Revoke Exploit",
  "DeFi Token Holder Token Sandwich Attack Exploit",
  "DeFi Token Holder Token Secure Transfer Exploit",
  "DeFi Token Holder Token Send Exploit",
  "DeFi Token Holder Token Smishing Exploit",
  "DeFi Token Holder Token Sniping Exploit",
  "DeFi Token Holder Token Social Engineering Exploit",
  "DeFi Token Holder Token Spear Phishing Exploit",
  "DeFi Token Holder Token Swap Exploit",
  "DeFi Token Holder Token Tailgating Exploit",
  "DeFi Token Holder Token Tampering",
  "DeFi Token Holder Token Theft",
  "DeFi Token Holder Token Transfer Exploit",
  "DeFi Token Holder Token Unlock Exploit",
  "DeFi Token Holder Token Vishing Exploit",
  "DeFi Token Holder Token Whaling Exploit",
  "DeFi Token Listing Exploit",
  "DeFi Token Lock Exploit",
  "DeFi Token Lockup Exploit",
  "DeFi Token Mint Exploit",
  "DeFi Token Minting Exploit",
  "DeFi Token Price Manipulation",
  "DeFi Token Reassignment Exploit",
  "DeFi Token Rebase Exploit",
  "DeFi Token Revoke Exploit",
  "DeFi Token Standard Exploit",
  "DeFi Token Swap Exploit",
  "DeFi Token Swap Front-Running",
  "DeFi Token Transfer Exploit",
  "DeFi Token Unlock Exploit",
  "DeFi Token Vesting Exploit",
  "DeFi Token Voting Exploit",
  "DeFi Underlying Asset Manipulation",
  "DeFi Vault Exploit",
  "DeFi Voting Power Exploit",
  "DeFi Yield Farming Contract Exploit",
  "DeFi Yield Farming Exploit",
  "DeFi Yield Optimizer Exploit",
  "Decentralized Access Control Exploit",
  "Decentralized Application (DApp) Malware",
  "Decentralized Authentication Exploit",
  "Decentralized Authorization Exploit",
  "Decentralized Autonomous Organization (DAO) Exploit",
  "Decentralized Blogging Exploit",
  "Decentralized CDN Exploit",
  "Decentralized Content Platform Exploit",
  "Decentralized Crowdfunding Exploit",
  "Decentralized DNS Exploit",
  "Decentralized Data Sharing Exploit",
  "Decentralized Exchange (DEX) API Exploit",
  "Decentralized Exchange (DEX) Arbitrage Exploit",
  "Decentralized Exchange (DEX) Back-End Exploit",
  "Decentralized Exchange (DEX) Bridge Exploit",
  "Decentralized Exchange (DEX) Cross-Chain Exploit",
  "Decentralized Exchange (DEX) Exploit",
  "Decentralized Exchange (DEX) Fee Exploit",
  "Decentralized Exchange (DEX) Flash Loan Attack",
  "Decentralized Exchange (DEX) Flash Loan Liquidity Exploit",
  "Decentralized Exchange (DEX) Front-End Exploit",
  "Decentralized Exchange (DEX) Front-Running",
  "Decentralized Exchange (DEX) Governance Attack",
  "Decentralized Exchange (DEX) Governance Token Exploit",
  "Decentralized Exchange (DEX) Leverage Exploit",
  "Decentralized Exchange (DEX) Liquidation Exploit",
  "Decentralized Exchange (DEX) Liquidity Drain",
  "Decentralized Exchange (DEX) Liquidity Incentive Exploit",
  "Decentralized Exchange (DEX) Liquidity Pool Exploit",
  "Decentralized Exchange (DEX) Margin Trading Exploit",
  "Decentralized Exchange (DEX) Order Book Exploit",
  "Decentralized Exchange (DEX) Order Matching Exploit",
  "Decentralized Exchange (DEX) Pair Exploit",
  "Decentralized Exchange (DEX) Pool Rebalancing Exploit",
  "Decentralized Exchange (DEX) Price Manipulation",
  "Decentralized Exchange (DEX) Reentrancy Attack",
  "Decentralized Exchange (DEX) Router Exploit",
  "Decentralized Exchange (DEX) Settlement Bridge Exploit",
  "Decentralized Exchange (DEX) Settlement Chain Exploit",
  "Decentralized Exchange (DEX) Settlement Data Tampering",
  "Decentralized Exchange (DEX) Settlement Delay Exploit",
  "Decentralized Exchange (DEX) Settlement Exploit",
  "Decentralized Exchange (DEX) Settlement Governance Exploit",
  "Decentralized Exchange (DEX) Settlement Manipulation",
  "Decentralized Exchange (DEX) Settlement Multi-Sig Exploit",
  "Decentralized Exchange (DEX) Settlement Override Exploit",
  "Decentralized Exchange (DEX) Settlement Protocol Exploit",
  "Decentralized Exchange (DEX) Settlement Replay Attack",
  "Decentralized Exchange (DEX) Settlement Timelock Exploit",
  "Decentralized Exchange (DEX) Settlement Token Access Control Exploit",
  "Decentralized Exchange (DEX) Settlement Token Approve Exploit",
  "Decentralized Exchange (DEX) Settlement Token Arithmetic Exploit",
  "Decentralized Exchange (DEX) Settlement Token Balance Manipulation",
  "Decentralized Exchange (DEX) Settlement Token Borrowing Exploit",
  "Decentralized Exchange (DEX) Settlement Token Burn Exploit",
  "Decentralized Exchange (DEX) Settlement Token Burning Exploit",
  "Decentralized Exchange (DEX) Settlement Token DecreaseAllowance Exploit",
  "Decentralized Exchange (DEX) Settlement Token EIP-20 Exploit",
  "Decentralized Exchange (DEX) Settlement Token EIP-2612 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-1155 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-1400 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit10 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit2 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit3 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit4 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit5 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit6 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit7 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit8 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-20 Permit9 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-223 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-721 Exploit",
  "Decentralized Exchange (DEX) Settlement Token ERC-777 Exploit",
  "Decentralized Exchange (DEX) Settlement Token Exploit",
  "Decentralized Exchange (DEX) Settlement Token Factory Exploit",
  "Decentralized Exchange (DEX) Settlement Token Farming Exploit",
  "Decentralized Exchange (DEX) Settlement Token Flash Loan Exploit",
  "Decentralized Exchange (DEX) Settlement Token Freezing Exploit",
  "Decentralized Exchange (DEX) Settlement Token Governance Exploit",
  "Decentralized Exchange (DEX) Settlement Token IncreaseAllowance Exploit",
  "Decentralized Exchange (DEX) Settlement Token Lending Exploit",
  "Decentralized Exchange (DEX) Settlement Token Lock Exploit",
  "Decentralized Exchange (DEX) Settlement Token Logic Exploit",
  "Decentralized Exchange (DEX) Settlement Token Mint Exploit",
  "Decentralized Exchange (DEX) Settlement Token Minting Exploit",
  "Decentralized Exchange (DEX) Settlement Token Overflows",
  "Decentralized Exchange (DEX) Settlement Token Permission Exploit",
  "Decentralized Exchange (DEX) Settlement Token Permit Exploit",
  "Decentralized Exchange (DEX) Settlement Token Proxy Exploit",
  "Decentralized Exchange (DEX) Settlement Token Reentrancy Exploit",
  "Decentralized Exchange (DEX) Settlement Token Staking Exploit",
  "Decentralized Exchange (DEX) Settlement Token Swap Exploit",
  "Decentralized Exchange (DEX) Settlement Token Transfer Exploit",
  "Decentralized Exchange (DEX) Settlement Token TransferFrom Exploit",
  "Decentralized Exchange (DEX) Settlement Token Underflows",
  "Decentralized Exchange (DEX) Settlement Token Unfreezing Exploit",
  "Decentralized Exchange (DEX) Settlement Token Unlock Exploit",
  "Decentralized Exchange (DEX) Settlement Token Upgrade Exploit",
  "Decentralized Exchange (DEX) Settlement Token Vesting Exploit",
  "Decentralized Exchange (DEX) Settlement Voting Exploit",
  "Decentralized Exchange (DEX) Smart Contract Exploit",
  "Decentralized Exchange (DEX) Smart Order Routing Exploit",
  "Decentralized Exchange (DEX) Token Swap Exploit",
  "Decentralized Finance (DeFi) Exploit",
  "Decentralized Finance (DeFi) Flash Loan Attack",
  "Decentralized Finance (DeFi) Flash Loan Exploit",
  "Decentralized Forum Exploit",
  "Decentralized Gaming Exploit",
  "Decentralized Identity (DID) Exploit",
  "Decentralized Insurance Exploit",
  "Decentralized Marketplace Exploit",
  "Decentralized Messaging Exploit",
  "Decentralized Prediction Market Exploit",
  "Decentralized Social Media Exploit",
  "Decentralized Storage Malware",
  "Decentralized Voting System Exploit",
  "Deep Learning Model Inversion Attack",
  "Deepfake Social Engineering",
  "Denial of Service (DoS)",
  "Deserialization Attack",
  "Dictionary Attack",
  "Differential Power Analysis (DPA)",
  "Digital Signage Hacking",
  "Digital Wallet Exploit",
  "Directory Traversal",
  "Distributed Denial of Service (DDoS)",
  "Domain Generation Algorithm (DGA) Exploit",
  "Domain Spoofing",
  "Drive-By .NET CLR Exploit",
  "Drive-By 5G Exploit",
  "Drive-By AI Exploit",
  "Drive-By API Rate Limiting Bypass",
  "Drive-By API Token Theft",
  "Drive-By ASIC Exploit",
  "Drive-By Accelerometer Exploit",
  "Drive-By Ad Filtering Exploit",
  "Drive-By Ambient Light Sensor Exploit",
  "Drive-By Anomaly Detection Exploit",
  "Drive-By Application Delivery Controller (ADC) Exploit",
  "Drive-By Archive Exploit",
  "Drive-By BIOS Exploit",
  "Drive-By BIOS Firmware Manipulation",
  "Drive-By Behavioral Analytics Exploit",
  "Drive-By Binary Exploit",
  "Drive-By Biometric Exploit",
  "Drive-By Blockchain Sybil Attack",
  "Drive-By Bluetooth Exploit",
  "Drive-By Bluetooth Sniffing",
  "Drive-By Boot Sector Exploit",
  "Drive-By Bootkit Exploit",
  "Drive-By Bootloader Exploit",
  "Drive-By Browser Autofill Exploit",
  "Drive-By Browser Bluetooth Exploit",
  "Drive-By Browser CORS Bypass",
  "Drive-By Browser Cache Exploit",
  "Drive-By Browser Camera Exploit",
  "Drive-By Browser Character Encoding Exploit",
  "Drive-By Browser Clipboard Exploit",
  "Drive-By Browser Content Security Policy (CSP) Bypass",
  "Drive-By Browser Content-Type Sniffing Exploit",
  "Drive-By Browser Cookie Exploit",
  "Drive-By Browser Extension Exploit",
  "Drive-By Browser Geolocation Exploit",
  "Drive-By Browser History Exploit",
  "Drive-By Browser Iframe Exploit",
  "Drive-By Browser IndexedDB Exploit",
  "Drive-By Browser Local Storage Exploit",
  "Drive-By Browser MIME Type Exploit",
  "Drive-By Browser Memory Exploit",
  "Drive-By Browser Microphone Exploit",
  "Drive-By Browser Plugin Exploit",
  "Drive-By Browser Popup Exploit",
  "Drive-By Browser Process Hijacking",
  "Drive-By Browser Push Notification Exploit",
  "Drive-By Browser Redirect Exploit",
  "Drive-By Browser Referrer Policy Exploit",
  "Drive-By Browser Same-Origin Policy (SOP) Bypass",
  "Drive-By Browser Sandbox Escape",
  "Drive-By Browser Screenshot Exploit",
  "Drive-By Browser Service Worker Exploit",
  "Drive-By Browser Session Hijacking",
  "Drive-By Browser Session Storage Exploit",
  "Drive-By Browser Storage Exploit",
  "Drive-By Browser Tab Exploit",
  "Drive-By Browser WebAssembly Exploit",
  "Drive-By Browser WebRTC Exploit",
  "Drive-By Browser WebSocket Exploit",
  "Drive-By Browser Window Exploit",
  "Drive-By Browser XSS Auditor Bypass",
  "Drive-By Bytecode Exploit",
  "Drive-By C++ VTable Poisoning",
  "Drive-By C++ Virtual Table Exploit",
  "Drive-By CSS Exploit",
  "Drive-By Canary Poisoning Attack",
  "Drive-By Certificate Authority Compromise",
  "Drive-By Certificate Pinning Bypass",
  "Drive-By Certificate Revocation List (CRL) Poisoning",
  "Drive-By Certificate Transparency Log Manipulation",
  "Drive-By Chakra Exploit",
  "Drive-By Cloud API Hijacking",
  "Drive-By Cloud Database Exploit",
  "Drive-By Cloud Function Injection",
  "Drive-By Cloud IAM Misconfiguration",
  "Drive-By Cloud Instance Metadata Exploit",
  "Drive-By Cloud Kubernetes Exploit",
  "Drive-By Cloud Metadata API Exploit",
  "Drive-By Cloud Multi-Cloud Exploit",
  "Drive-By Cloud Serverless Function Exploit",
  "Drive-By Cloud Service Mesh Exploit",
  "Drive-By Cloud Storage Bucket Exploit",
  "Drive-By Code Injection via Bytecode",
  "Drive-By Computer Vision Exploit",
  "Drive-By Constructive Jump-Oriented Programming",
  "Drive-By Content Filtering Exploit",
  "Drive-By Cryptography Exploit",
  "Drive-By DANE Exploit",
  "Drive-By DApp Front-End Exploit",
  "Drive-By DNS over HTTPS (DoH) Exploit",
  "Drive-By DNS over TLS (DoT) Exploit",
  "Drive-By DNSSEC Bypass",
  "Drive-By DOM Clobbering Attack",
  "Drive-By DOM Event Injection",
  "Drive-By DOM Mutation Exploit",
  "Drive-By DOM Traversal Exploit",
  "Drive-By DOM-Based Cross-Site Scripting (DOM-XSS)",
  "Drive-By Data AMQP Exploit",
  "Drive-By Data Aggregation Exploit",
  "Drive-By Data Analysis Exploit",
  "Drive-By Data Anonymization Exploit",
  "Drive-By Data Archiving Exploit",
  "Drive-By Data Array Exploit",
  "Drive-By Data Availability Exploit",
  "Drive-By Data Avro Exploit",
  "Drive-By Data BGP Exploit",
  "Drive-By Data BSON Exploit",
  "Drive-By Data Backup Exploit",
  "Drive-By Data Batch Exploit",
  "Drive-By Data Binary Exploit",
  "Drive-By Data Boolean Exploit",
  "Drive-By Data CBOR Exploit",
  "Drive-By Data CDP Exploit",
  "Drive-By Data CSV Exploit",
  "Drive-By Data Cap’n Proto Exploit",
  "Drive-By Data Cleartext Exploit",
  "Drive-By Data CoAP Exploit",
  "Drive-By Data Column-Family Exploit",
  "Drive-By Data Compliance Exploit",
  "Drive-By Data Compressed Exploit",
  "Drive-By Data Confidentiality Exploit",
  "Drive-By Data DHCP Exploit",
  "Drive-By Data DNS Exploit",
  "Drive-By Data DTLS Exploit",
  "Drive-By Data Decryption Exploit",
  "Drive-By Data Delta Exploit",
  "Drive-By Data Denormalization Exploit",
  "Drive-By Data Differential Exploit",
  "Drive-By Data Disposal Exploit",
  "Drive-By Data Document Exploit",
  "Drive-By Data EIGRP Exploit",
  "Drive-By Data Encrypted Exploit",
  "Drive-By Data Encryption Exploit",
  "Drive-By Data EtherChannel Exploit",
  "Drive-By Data FTP Bounce Exploit",
  "Drive-By Data FTP Exploit",
  "Drive-By Data Fabric Exploit",
  "Drive-By Data Flat Exploit",
  "Drive-By Data FlatBuffers Exploit",
  "Drive-By Data Flow Exploit",
  "Drive-By Data Full Exploit",
  "Drive-By Data Governance Exploit",
  "Drive-By Data Graph Exploit",
  "Drive-By Data GraphQL Exploit",
  "Drive-By Data H.323 Exploit",
  "Drive-By Data HTTP ACL Exploit",
  "Drive-By Data HTTP CHECKIN Exploit",
  "Drive-By Data HTTP CHECKOUT Exploit",
  "Drive-By Data HTTP CONNECT Exploit",
  "Drive-By Data HTTP COPY Exploit",
  "Drive-By Data HTTP DELETE Exploit",
  "Drive-By Data HTTP Exploit",
  "Drive-By Data HTTP HEAD Exploit",
  "Drive-By Data HTTP LOCK Exploit",
  "Drive-By Data HTTP MERGE Exploit",
  "Drive-By Data HTTP MERGEBASE Exploit",
  "Drive-By Data HTTP MKACTIVITY Exploit",
  "Drive-By Data HTTP MKAGGREGATE Exploit",
  "Drive-By Data HTTP MKANALYSIS Exploit",
  "Drive-By Data HTTP MKAPPLICATION Exploit",
  "Drive-By Data HTTP MKAPPOINTMENT Exploit",
  "Drive-By Data HTTP MKCALENDAR Exploit",
  "Drive-By Data HTTP MKCELL Exploit",
  "Drive-By Data HTTP MKCHART Exploit",
  "Drive-By Data HTTP MKCOL Exploit",
  "Drive-By Data HTTP MKCOLLECTION Exploit",
  "Drive-By Data HTTP MKCOLUMN Exploit",
  "Drive-By Data HTTP MKCOMPUTE Exploit",
  "Drive-By Data HTTP MKCONFIG Exploit",
  "Drive-By Data HTTP MKCONFIGURATION Exploit",
  "Drive-By Data HTTP MKCONTACTS Exploit",
  "Drive-By Data HTTP MKDASHBOARD Exploit",
  "Drive-By Data HTTP MKDATAADAPTIVE Exploit",
  "Drive-By Data HTTP MKDATAALERTING Exploit",
  "Drive-By Data HTTP MKDATAANALYTICS Exploit",
  "Drive-By Data HTTP MKDATAANDROID Exploit",
  "Drive-By Data HTTP MKDATAASSURANCE Exploit",
  "Drive-By Data HTTP MKDATAAUDITING Exploit",
  "Drive-By Data HTTP MKDATAAUTOMATION Exploit",
  "Drive-By Data HTTP MKDATAAVAILABILITY Exploit",
  "Drive-By Data HTTP MKDATABASE Exploit",
  "Drive-By Data HTTP MKDATABLACKLIST Exploit",
  "Drive-By Data HTTP MKDATABORDER Exploit",
  "Drive-By Data HTTP MKDATABOTTOM Exploit",
  "Drive-By Data HTTP MKDATABOTTOMLEFT Exploit",
  "Drive-By Data HTTP MKDATABOTTOMRIGHT Exploit",
  "Drive-By Data HTTP MKDATACATALOG Exploit",
  "Drive-By Data HTTP MKDATACENTER Exploit",
  "Drive-By Data HTTP MKDATACHART Exploit",
  "Drive-By Data HTTP MKDATACLEANING Exploit",
  "Drive-By Data HTTP MKDATACOLLABORATION Exploit",
  "Drive-By Data HTTP MKDATACOLOR Exploit",
  "Drive-By Data HTTP MKDATACOMPLIANCE Exploit",
  "Drive-By Data HTTP MKDATACONSOLIDATION Exploit",
  "Drive-By Data HTTP MKDATACONTROL Exploit",
  "Drive-By Data HTTP MKDATACUSTOM Exploit",
  "Drive-By Data HTTP MKDATADASHBOARD Exploit",
  "Drive-By Data HTTP MKDATADISTRIBUTION Exploit",
  "Drive-By Data HTTP MKDATAEFFICIENCY Exploit",
  "Drive-By Data HTTP MKDATAENRICHMENT Exploit",
  "Drive-By Data HTTP MKDATAETHERNET Exploit",
  "Drive-By Data HTTP MKDATAEXCHANGE Exploit",
  "Drive-By Data HTTP MKDATAEXPLORE Exploit",
  "Drive-By Data HTTP MKDATAFILTER Exploit",
  "Drive-By Data HTTP MKDATAFILTERING Exploit",
  "Drive-By Data HTTP MKDATAFIXED Exploit",
  "Drive-By Data HTTP MKDATAFLUID Exploit",
  "Drive-By Data HTTP MKDATAFONT Exploit",
  "Drive-By Data HTTP MKDATAFONT SIZE Exploit",
  "Drive-By Data HTTP MKDATAFORMAT Exploit",
  "Drive-By Data HTTP MKDATAFORTIFICATION Exploit",
  "Drive-By Data HTTP MKDATAFULLWIDTH Exploit",
  "Drive-By Data HTTP MKDATAFUSION Exploit",
  "Drive-By Data HTTP MKDATAFUTURE Exploit",
  "Drive-By Data HTTP MKDATAGOVERNANCE Exploit",
  "Drive-By Data HTTP MKDATAGRAPH Exploit",
  "Drive-By Data HTTP MKDATAGROUP Exploit",
  "Drive-By Data HTTP MKDATAHALFHORIZONTAL Exploit",
  "Drive-By Data HTTP MKDATAHALFVERTICAL Exploit",
  "Drive-By Data HTTP MKDATAHALFWIDTH Exploit",
  "Drive-By Data HTTP MKDATAINNOVATION Exploit",
  "Drive-By Data HTTP MKDATAINTEGRATION Exploit",
  "Drive-By Data HTTP MKDATAINTERNET Exploit",
  "Drive-By Data HTTP MKDATAIOS Exploit",
  "Drive-By Data HTTP MKDATAJOIN Exploit",
  "Drive-By Data HTTP MKDATALABEL Exploit",
  "Drive-By Data HTTP MKDATALANDSCAPE Exploit",
  "Drive-By Data HTTP MKDATALEFT Exploit",
  "Drive-By Data HTTP MKDATALEGACY Exploit",
  "Drive-By Data HTTP MKDATALINUX Exploit",
  "Drive-By Data HTTP MKDATALOGGING Exploit",
  "Drive-By Data HTTP MKDATAMAC Exploit",
  "Drive-By Data HTTP MKDATAMANAGEMENT Exploit",
  "Drive-By Data HTTP MKDATAMANIPULATION Exploit",
  "Drive-By Data HTTP MKDATAMAP Exploit",
  "Drive-By Data HTTP MKDATAMAPPING Exploit",
  "Drive-By Data HTTP MKDATAMARGIN Exploit",
  "Drive-By Data HTTP MKDATAMART Exploit",
  "Drive-By Data HTTP MKDATAMIDDLE Exploit",
  "Drive-By Data HTTP MKDATAMIGRATION Exploit",
  "Drive-By Data HTTP MKDATAMINING Exploit",
  "Drive-By Data HTTP MKDATAMOBILE Exploit",
  "Drive-By Data HTTP MKDATAMODEL Exploit",
  "Drive-By Data HTTP MKDATAMODERN Exploit",
  "Drive-By Data HTTP MKDATAMONITORING Exploit",
  "Drive-By Data HTTP MKDATANETWORK Exploit",
  "Drive-By Data HTTP MKDATANEXTGEN Exploit",
  "Drive-By Data HTTP MKDATANOTIFICATION Exploit",
  "Drive-By Data HTTP MKDATAPADDING Exploit",
  "Drive-By Data HTTP MKDATAPANEL Exploit",
  "Drive-By Data HTTP MKDATAPC Exploit",
  "Drive-By Data HTTP MKDATAPERFORMANCE Exploit",
  "Drive-By Data HTTP MKDATAPERSISTENCE Exploit",
  "Drive-By Data HTTP MKDATAPIPING Exploit",
  "Drive-By Data HTTP MKDATAPIVOT Exploit",
  "Drive-By Data HTTP MKDATAPOINT Exploit",
  "Drive-By Data HTTP MKDATAPORTRAIT Exploit",
  "Drive-By Data HTTP MKDATAPRIVACY Exploit",
  "Drive-By Data HTTP MKDATAPRIVATE Exploit",
  "Drive-By Data HTTP MKDATAPROCESSING Exploit",
  "Drive-By Data HTTP MKDATAPRODUCTIVITY Exploit",
  "Drive-By Data HTTP MKDATAPROTECTION Exploit",
  "Drive-By Data HTTP MKDATAPUBLIC Exploit",
  "Drive-By Data HTTP MKDATAQUALITY Exploit",
  "Drive-By Data HTTP MKDATAREAL Exploit",
  "Drive-By Data HTTP MKDATARECEIVER Exploit",
  "Drive-By Data HTTP MKDATARELIABILITY Exploit",
  "Drive-By Data HTTP MKDATARESILIENCY Exploit",
  "Drive-By Data HTTP MKDATARESPONSIVE Exploit",
  "Drive-By Data HTTP MKDATARIGHT Exploit",
  "Drive-By Data HTTP MKDATARISK Exploit",
  "Drive-By Data HTTP MKDATARUNTIME Exploit",
  "Drive-By Data HTTP MKDATASAFE Exploit",
  "Drive-By Data HTTP MKDATASCALABILITY Exploit",
  "Drive-By Data HTTP MKDATASECURITY Exploit",
  "Drive-By Data HTTP MKDATASECURITYALERTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYASSESSMENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYAUDIT Exploit",
  "Drive-By Data HTTP MKDATASECURITYAWARENESS Exploit",
  "Drive-By Data HTTP MKDATASECURITYBEST PRACTICES Exploit",
  "Drive-By Data HTTP MKDATASECURITYBREACH Exploit",
  "Drive-By Data HTTP MKDATASECURITYCERTIFICATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYCOMPLIANCE Exploit",
  "Drive-By Data HTTP MKDATASECURITYCOMPLIANCEAUDIT Exploit",
  "Drive-By Data HTTP MKDATASECURITYCONTINUITY Exploit",
  "Drive-By Data HTTP MKDATASECURITYCONTROLS Exploit",
  "Drive-By Data HTTP MKDATASECURITYEVENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYFORTIFICATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYFRAMEWORK Exploit",
  "Drive-By Data HTTP MKDATASECURITYGUIDELINES Exploit",
  "Drive-By Data HTTP MKDATASECURITYINCIDENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYLOG Exploit",
  "Drive-By Data HTTP MKDATASECURITYMITIGATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYMONITORING Exploit",
  "Drive-By Data HTTP MKDATASECURITYPENETRATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYPOLICY Exploit",
  "Drive-By Data HTTP MKDATASECURITYPROCEDURES Exploit",
  "Drive-By Data HTTP MKDATASECURITYRECOVERY Exploit",
  "Drive-By Data HTTP MKDATASECURITYREGULATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYRESILIENCY Exploit",
  "Drive-By Data HTTP MKDATASECURITYREVIEW Exploit",
  "Drive-By Data HTTP MKDATASECURITYRISK Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYALERTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYASSESSMENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYBEST PRACTICES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYCERTIFICATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYCOMPLIANCEAUDIT Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYCONTINUITY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYCONTROLS Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYGUIDELINES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYMONITORING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYPOLICY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYPROCEDURES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYRECOVERY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYALERTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYASSESSMENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYBEST PRACTICES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYCERTIFICATION Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYCOMPLIANCEAUDIT Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYCONTINUITY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYCONTROLS Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYGUIDELINES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYMONITORING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYPOLICY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYPROCEDURES Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYRECOVERY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYALERTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYASSESSMENT Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYCONTINUITY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYMONITORING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYRECOVERY Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYSECURITYTESTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYSECURITYTESTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSECURITYTESTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYSTANDARD Exploit",
  "Drive-By Data HTTP MKDATASECURITYTESTING Exploit",
  "Drive-By Data HTTP MKDATASECURITYTRAINING Exploit",
  "Drive-By Data HTTP MKDATASECURITYVIOLATION Exploit",
  "Drive-By Data HTTP MKDATASENSITIVITY Exploit",
  "Drive-By Data HTTP MKDATASERIES Exploit",
  "Drive-By Data HTTP MKDATASORT Exploit",
  "Drive-By Data HTTP MKDATASOURCE Exploit",
  "Drive-By Data HTTP MKDATASTREAM Exploit",
  "Drive-By Data HTTP MKDATASTYLE Exploit",
  "Drive-By Data HTTP MKDATASUBTITLE Exploit",
  "Drive-By Data HTTP MKDATATABLATE Exploit",
  "Drive-By Data HTTP MKDATATABLE Exploit",
  "Drive-By Data HTTP MKDATATABLET Exploit",
  "Drive-By Data HTTP MKDATATARGET Exploit",
  "Drive-By Data HTTP MKDATATEXT Exploit",
  "Drive-By Data HTTP MKDATATHREE COLUMN Exploit",
  "Drive-By Data HTTP MKDATATIMESHIFT Exploit",
  "Drive-By Data HTTP MKDATATITLE Exploit",
  "Drive-By Data HTTP MKDATATOP Exploit",
  "Drive-By Data HTTP MKDATATOPLEFT Exploit",
  "Drive-By Data HTTP MKDATATOPRIGHT Exploit",
  "Drive-By Data HTTP MKDATATRANSFORMATION Exploit",
  "Drive-By Data HTTP MKDATATWO COLUMN Exploit",
  "Drive-By Data HTTP MKDATATYPE Exploit",
  "Drive-By Data HTTP MKDATAVALIDATION Exploit",
  "Drive-By Data HTTP MKDATAVIEW Exploit",
  "Drive-By Data HTTP MKDATAVIRTUAL Exploit",
  "Drive-By Data HTTP MKDATAVISUALIZATION Exploit",
  "Drive-By Data HTTP MKDATAVIZ Exploit",
  "Drive-By Data HTTP MKDATAWAREHOUSE Exploit",
  "Drive-By Data HTTP MKDATAWEB Exploit",
  "Drive-By Data HTTP MKDATAWHITELIST Exploit",
  "Drive-By Data HTTP MKDATAWIFI Exploit",
  "Drive-By Data HTTP MKDATAWINDOWS Exploit",
  "Drive-By Data HTTP MKDATAWIRELESS Exploit",
  "Drive-By Data HTTP MKDEVICE Exploit",
  "Drive-By Data HTTP MKDOC Exploit",
  "Drive-By Data HTTP MKDRAFT Exploit",
  "Drive-By Data HTTP MKEVENT Exploit",
  "Drive-By Data HTTP MKEXCEPT Exploit",
  "Drive-By Data HTTP MKGRAPH Exploit",
  "Drive-By Data HTTP MKGROUP Exploit",
  "Drive-By Data HTTP MKINDEX Exploit",
  "Drive-By Data HTTP MKINTERSECT Exploit",
  "Drive-By Data HTTP MKJOIN Exploit",
  "Drive-By Data HTTP MKLICENSE Exploit",
  "Drive-By Data HTTP MKLOM Exploit",
  "Drive-By Data HTTP MKMAP Exploit",
  "Drive-By Data HTTP MKMEMBER Exploit",
  "Drive-By Data HTTP MKMETADATA Exploit",
  "Drive-By Data HTTP MKNETWORK Exploit",
  "Drive-By Data HTTP MKNOTE Exploit",
  "Drive-By Data HTTP MKPERMISSION Exploit",
  "Drive-By Data HTTP MKPOLICY Exploit",
  "Drive-By Data HTTP MKPOWERBI Exploit",
  "Drive-By Data HTTP MKPROFILE Exploit",
  "Drive-By Data HTTP MKQUERY Exploit",
  "Drive-By Data HTTP MKREPORT Exploit",
  "Drive-By Data HTTP MKREQUEST Exploit",
  "Drive-By Data HTTP MKRESOURCE Exploit",
  "Drive-By Data HTTP MKRESOURCEGROUP Exploit",
  "Drive-By Data HTTP MKROLE Exploit",
  "Drive-By Data HTTP MKROW Exploit",
  "Drive-By Data HTTP MKRULE Exploit",
  "Drive-By Data HTTP MKSCHEMA Exploit",
  "Drive-By Data HTTP MKSERVICE Exploit",
  "Drive-By Data HTTP MKSETTINGS Exploit",
  "Drive-By Data HTTP MKSTATE Exploit",
  "Drive-By Data HTTP MKSTATUS Exploit",
  "Drive-By Data HTTP MKTABLE Exploit",
  "Drive-By Data HTTP MKTABLEAU Exploit",
  "Drive-By Data HTTP MKTAGNAME Exploit",
  "Drive-By Data HTTP MKTASK Exploit",
  "Drive-By Data HTTP MKUNION Exploit",
  "Drive-By Data HTTP MKVERSION Exploit",
  "Drive-By Data HTTP MKVIEW Exploit",
  "Drive-By Data HTTP MKWORKSPACE Exploit",
  "Drive-By Data HTTP MOVE Exploit",
  "Drive-By Data HTTP OPTIONS Exploit",
  "Drive-By Data HTTP ORDERPATCH Exploit",
  "Drive-By Data HTTP PATCH Exploit",
  "Drive-By Data HTTP PROPFIND Exploit",
  "Drive-By Data HTTP PROPPATCH Exploit",
  "Drive-By Data HTTP PUT Exploit",
  "Drive-By Data HTTP REPORT Exploit",
  "Drive-By Data HTTP SEARCH Exploit",
  "Drive-By Data HTTP TRACE Exploit",
  "Drive-By Data HTTP TRACK Exploit",
  "Drive-By Data HTTP UNLOCK Exploit",
  "Drive-By Data HTTP UPDATE Exploit",
  "Drive-By Data HTTP VERSION-CONTROL Exploit",
  "Drive-By Data HTTP/2 Exploit",
  "Drive-By Data HTTP/3 Exploit",
  "Drive-By Data HTTPS Exploit",
  "Drive-By Data Hierarchical Exploit",
  "Drive-By Data IAX Exploit",
  "Drive-By Data IMAP Exploit",
  "Drive-By Data IRC Exploit",
  "Drive-By Data Incremental Exploit",
  "Drive-By Data Indexed Exploit",
  "Drive-By Data Integration Exploit",
  "Drive-By Data Integrity Exploit",
  "Drive-By Data JSON Exploit",
  "Drive-By Data Key-Value Exploit",
  "Drive-By Data LACP Exploit",
  "Drive-By Data LLDP Exploit",
  "Drive-By Data Lake Exploit",
  "Drive-By Data Linking Exploit",
  "Drive-By Data Log Exploit",
  "Drive-By Data MEGACO Exploit",
  "Drive-By Data MGCP Exploit",
  "Drive-By Data MPLS Exploit",
  "Drive-By Data MQTT Exploit",
  "Drive-By Data MSTP Exploit",
  "Drive-By Data Masking Exploit",
  "Drive-By Data Mesh Exploit",
  "Drive-By Data Metadata Exploit",
  "Drive-By Data Migration Exploit",
  "Drive-By Data Mining Exploit",
  "Drive-By Data MsgPack Exploit",
  "Drive-By Data Multimedia Exploit",
  "Drive-By Data NTP Exploit",
  "Drive-By Data NoSQL Exploit",
  "Drive-By Data Non-Relational Exploit",
  "Drive-By Data Normalization Exploit",
  "Drive-By Data Numeric Exploit",
  "Drive-By Data ORC Exploit",
  "Drive-By Data OSPF Exploit",
  "Drive-By Data Obfuscated Exploit",
  "Drive-By Data Obfuscation Exploit",
  "Drive-By Data Object Exploit",
  "Drive-By Data On-Demand Exploit",
  "Drive-By Data POP3 Exploit",
  "Drive-By Data Parquet Exploit",
  "Drive-By Data Partitioning Exploit",
  "Drive-By Data Pipeline Exploit",
  "Drive-By Data Privacy Exploit",
  "Drive-By Data Protocol Buffers Exploit",
  "Drive-By Data Pseudonymization Exploit",
  "Drive-By Data QUIC Exploit",
  "Drive-By Data REST API Exploit",
  "Drive-By Data RIP Exploit",
  "Drive-By Data RPC Exploit",
  "Drive-By Data RSTP Exploit",
  "Drive-By Data RTCP Exploit",
  "Drive-By Data RTP Exploit",
  "Drive-By Data Real-Time Exploit",
  "Drive-By Data Recovery Exploit",
  "Drive-By Data Redundancy Exploit",
  "Drive-By Data Referencing Exploit",
  "Drive-By Data Relational Exploit",
  "Drive-By Data Replication Exploit",
  "Drive-By Data Reporting Exploit",
  "Drive-By Data Retention Exploit",
  "Drive-By Data SBE Exploit",
  "Drive-By Data SCP Exploit",
  "Drive-By Data SFTP Exploit",
  "Drive-By Data SHTTP Exploit",
  "Drive-By Data SIP Exploit",
  "Drive-By Data SMTP Exploit",
  "Drive-By Data SNMP Exploit",
  "Drive-By Data SNTP Exploit",
  "Drive-By Data SOAP API Exploit",
  "Drive-By Data SQL Exploit",
  "Drive-By Data SSH Exploit",
  "Drive-By Data SSL Exploit",
  "Drive-By Data SSP Exploit",
  "Drive-By Data SSV Exploit",
  "Drive-By Data STP Exploit",
  "Drive-By Data Scheduled Exploit",
  "Drive-By Data Sensor Exploit",
  "Drive-By Data Sharding Exploit",
  "Drive-By Data Snapshot Exploit",
  "Drive-By Data Spatial Exploit",
  "Drive-By Data Stream Exploit",
  "Drive-By Data Summarization Exploit",
  "Drive-By Data TLS Exploit",
  "Drive-By Data TOML Exploit",
  "Drive-By Data TSV Exploit",
  "Drive-By Data Telnet Exploit",
  "Drive-By Data Temporal Exploit",
  "Drive-By Data Text Exploit",
  "Drive-By Data Thrift Exploit",
  "Drive-By Data Time-Series Exploit",
  "Drive-By Data Transaction Exploit",
  "Drive-By Data Transformation Exploit",
  "Drive-By Data UBJSON Exploit",
  "Drive-By Data Uncompressed Exploit",
  "Drive-By Data Unencrypted Exploit",
  "Drive-By Data Unindexed Exploit",
  "Drive-By Data VLAN Exploit",
  "Drive-By Data VTP Exploit",
  "Drive-By Data Versioning Exploit",
  "Drive-By Data Visualization Exploit",
  "Drive-By Data Warehousing Exploit",
  "Drive-By Data WebSocket Exploit",
  "Drive-By Data XML Exploit",
  "Drive-By Data XMPP Exploit",
  "Drive-By Data YAML Exploit",
  "Drive-By Data gRPC Exploit",
  "Drive-By Decentralized Network Disruption",
  "Drive-By Decryption Exploit",
  "Drive-By Deep Learning Exploit",
  "Drive-By Digital Certificate Manipulation",
  "Drive-By Disk Exploit",
  "Drive-By DoH/DNS Exploit",
  "Drive-By Download",
  "Drive-By Dynamic Link Library (DLL) Injection",
  "Drive-By ELF File Exploit",
  "Drive-By Embedded System Exploit",
  "Drive-By Encrypted DNS Exploit",
  "Drive-By Encryption Exploit",
  "Drive-By Event Exploit",
  "Drive-By Exception Exploit",
  "Drive-By Exploit",
  "Drive-By FPGA Exploit",
  "Drive-By Facial Recognition Exploit",
  "Drive-By File Descriptor Exploit",
  "Drive-By File Handle Exploit",
  "Drive-By File Locking Exploit",
  "Drive-By File System Exploit",
  "Drive-By Filesystem API Abuse",
  "Drive-By Firewall Exploit",
  "Drive-By Firmware Exploit",
  "Drive-By Flash Exploit",
  "Drive-By Fraud Detection Exploit",
  "Drive-By Function Pointer Exploit",
  "Drive-By GPS Exploit",
  "Drive-By GPT Exploit",
  "Drive-By Generative Adversarial Network (GAN) Exploit",
  "Drive-By Gyroscope Exploit",
  "Drive-By HTML Exploit",
  "Drive-By Hardware Security Module (HSM) Exploit",
  "Drive-By Hardware-Based Keylogging",
  "Drive-By Hashing Exploit",
  "Drive-By Humidity Sensor Exploit",
  "Drive-By Hypervisor Level Malware",
  "Drive-By ISO File Exploit",
  "Drive-By Identity Federation Exploit",
  "Drive-By Image Exploit",
  "Drive-By Image Recognition Exploit",
  "Drive-By Indirect Jump Exploit",
  "Drive-By Inter-Process Communication (IPC) Exploit",
  "Drive-By Intrusion Detection Exploit",
  "Drive-By Intrusion Prevention Exploit",
  "Drive-By JIT Spraying Attack",
  "Drive-By JIT-ROP Exploit",
  "Drive-By JSON Exploit",
  "Drive-By JWT Token Tampering",
  "Drive-By Java Virtual Machine (JVM) Exploit",
  "Drive-By JavaScript Engine Exploit",
  "Drive-By JavaScript Exploit",
  "Drive-By JavaScript Garbage Collection Exploit",
  "Drive-By JavaScript Just-In-Time (JIT) Exploit",
  "Drive-By Jump-Following Exploit",
  "Drive-By Jump-Oriented Programming (JOP) Chain",
  "Drive-By Jump-Table Manipulation",
  "Drive-By Just-In-Time (JIT) ROP Attack",
  "Drive-By LTE Exploit",
  "Drive-By LoRaWAN Exploit",
  "Drive-By Load Balancer Exploit",
  "Drive-By MBR Exploit",
  "Drive-By Mach-O File Exploit",
  "Drive-By Machine Learning Exploit",
  "Drive-By Magnetometer Exploit",
  "Drive-By Malware Download",
  "Drive-By Malware Filtering Exploit",
  "Drive-By Memory-Mapped File Exploit",
  "Drive-By Mesh Network Exploit",
  "Drive-By Message Queue Exploit",
  "Drive-By Microservice Exploit",
  "Drive-By Motion Sensor Exploit",
  "Drive-By Multi-Factor Authentication (MFA) Bypass",
  "Drive-By Multi-Tenant Exploit",
  "Drive-By Mutex Exploit",
  "Drive-By NB-IoT Exploit",
  "Drive-By NFC Exploit",
  "Drive-By NFC Relay Attack",
  "Drive-By Named Pipe Exploit",
  "Drive-By Natural Language Processing (NLP) Exploit",
  "Drive-By Network Exploit",
  "Drive-By Network Interface Card (NIC) Exploit",
  "Drive-By Neural Network Exploit",
  "Drive-By OAuth Consent Screen Exploit",
  "Drive-By OAuth Token Hijacking",
  "Drive-By Object Detection Exploit",
  "Drive-By Office Document Exploit",
  "Drive-By Onion Router Exploit",
  "Drive-By Onion Routing Exploit",
  "Drive-By Over-the-Air (OTA) Update Exploit",
  "Drive-By PDF Exploit",
  "Drive-By PE File Exploit",
  "Drive-By PHP Zend Engine Exploit",
  "Drive-By Partition Exploit",
  "Drive-By Pattern Recognition Exploit",
  "Drive-By Phishing",
  "Drive-By Phishing Filtering Exploit",
  "Drive-By Predictive Analytics Exploit",
  "Drive-By Pressure Sensor Exploit",
  "Drive-By Proximity Sensor Exploit",
  "Drive-By Proxy Chain Exploit",
  "Drive-By Proxy Exploit",
  "Drive-By Public Key Infrastructure (PKI) Exploit",
  "Drive-By Python Bytecode Exploit",
  "Drive-By QR Code Injection",
  "Drive-By RAR Exploit",
  "Drive-By RFID Exploit",
  "Drive-By RFID Spoofing",
  "Drive-By Recommendation Engine Exploit",
  "Drive-By Reflection-based Code Injection",
  "Drive-By Reinforcement Learning Exploit",
  "Drive-By Return-to-GOT Attack",
  "Drive-By Return-to-PLT Attack",
  "Drive-By Reverse Engineering Attack",
  "Drive-By Reverse Proxy Exploit",
  "Drive-By Ruby Interpreter Exploit",
  "Drive-By Runtime Code Modification",
  "Drive-By SAML Token Theft",
  "Drive-By SSL Renegotiation Exploit",
  "Drive-By SVG Exploit",
  "Drive-By Script Injection",
  "Drive-By Secure Boot Bypass",
  "Drive-By Secure Boot Exploit",
  "Drive-By Self-Modifying Code Exploit",
  "Drive-By Semaphore Exploit",
  "Drive-By Sentiment Analysis Exploit",
  "Drive-By Session Token Prediction",
  "Drive-By Shared Memory Exploit",
  "Drive-By Sigfox Exploit",
  "Drive-By Signal Exploit",
  "Drive-By Single Sign-On (SSO) Exploit",
  "Drive-By Smart Card Exploit",
  "Drive-By Smart Contract Fuzzing",
  "Drive-By Software Update Exploit",
  "Drive-By Spam Filtering Exploit",
  "Drive-By Speech Recognition Exploit",
  "Drive-By SpiderMonkey Exploit",
  "Drive-By Stack Canaries Exploit",
  "Drive-By Stack Canary Bypass",
  "Drive-By Stack Canary Exploit",
  "Drive-By Stack Frame Manipulation",
  "Drive-By Stack Overflow Exploit",
  "Drive-By Stack Probing Attack",
  "Drive-By Stack ROP Exploit",
  "Drive-By Stack Smashing Bypass",
  "Drive-By Stack Tracing Exploit",
  "Drive-By Stack Unwinding Attack",
  "Drive-By Steganography Exploit",
  "Drive-By System Firmware Rootkit",
  "Drive-By TLS Fingerprinting Exploit",
  "Drive-By TPM Exploit",
  "Drive-By Temperature Sensor Exploit",
  "Drive-By Text Recognition Exploit",
  "Drive-By Token Replay Attack",
  "Drive-By Tokenization Exploit",
  "Drive-By Tor Exit Node Exploit",
  "Drive-By Tor Exploit",
  "Drive-By Transformer Model Exploit",
  "Drive-By Trusted Platform Module (TPM) Exploit",
  "Drive-By UEFI Exploit",
  "Drive-By UEFI Firmware Exploit",
  "Drive-By UNIX Domain Socket Exploit",
  "Drive-By V8 Engine Exploit",
  "Drive-By VPN Encryption Exploit",
  "Drive-By VPN Exploit",
  "Drive-By VTable Hijacking",
  "Drive-By Video Exploit",
  "Drive-By Virtual Desktop Infrastructure (VDI) Exploit",
  "Drive-By Virtual File System Exploit",
  "Drive-By Virtual Function Exploit",
  "Drive-By Virtual Machine Escape",
  "Drive-By Voice Recognition Exploit",
  "Drive-By Volume Exploit",
  "Drive-By WAF Rule Exploit",
  "Drive-By Web Application Firewall (WAF) Bypass",
  "Drive-By Web of Trust Exploit",
  "Drive-By Wi-Fi 6 Exploit",
  "Drive-By Wi-Fi 7 Exploit",
  "Drive-By Wireless Exploit",
  "Drive-By XML Exploit",
  "Drive-By Z-Wave Exploit",
  "Drive-By ZIP Exploit",
  "Drive-By Zigbee Exploit",
  "Dumpster Diving",
  "E-Ink Device Malware",
  "EDNS0 Client Subnet Attack",
  "Eavesdropping Attack",
  "Edge Computing Attack",
  "Electric Vehicle Charging Station Exploit",
  "Electromagnetic Analysis (EMA)",
  "Electronic Paper Display Exploit",
  "Enumeration",
  "Evil Routing Advertisement",
  "Evil Twin Attack",
  "Exploit Kit Deployment",
  "Exploitation",
  "FREAK Attack",
  "Fake News Propagation",
  "Fake Profiles Creation",
  "Fake Software Update",
  "File Inclusion",
  "Filecoin Exploit",
  "Fileless Malware",
  "Fileless Malware Execution",
  "Firmware Downgrade Attack",
  "Firmware Malware Injection",
  "Firmware Overwrite",
  "Firmware Reverse Engineering",
  "Firmware Signature Bypass",
  "Firmware Tampering",
  "Fitness Tracker Malware",
  "Footprinting",
  "Foreshadow Attack",
  "Foreshadow Variant 1",
  "Foreshadow-NG Attack",
  "Foreshadow-NG Variant A",
  "Foreshadow-NG Variant B",
  "Foreshadow-ST Attack",
  "Foreshadow-ST Variant A",
  "Foreshadow-ST Variant B",
  "Format String Attack",
  "Format String Vulnerability",
  "Formjacking",
  "Fraggle Attack",
  "GPU Mining Malware",
  "GRE Tunnel Exploitation",
  "Gadgets in Memory",
  "Ghost Load",
  "Golden Ticket Attack",
  "Golden Ticket Forgery",
  "HTTP Flood",
  "HTTP Parameter Pollution (HPP)",
  "HTTP Request Smuggling",
  "HTTP Response Splitting",
  "HTTP/2 Flood",
  "Hardware Backdoor",
  "Hardware Keylogger",
  "Hardware Rootkit",
  "Hardware Supply Chain Attack",
  "Hardware Trojans",
  "Hardware-Based Malware",
  "Health Monitoring Device Exploit",
  "Heap Overflow",
  "Heap Spraying",
  "Heartbleed Attack",
  "Hijacked Wi-Fi Networks",
  "Holographic Display Exploit",
  "Home Automation System Exploit",
  "ICMP Address Mask Reply Flood",
  "ICMP Address Mask Request Flood",
  "ICMP Datagram Too Big Flood",
  "ICMP Datagram Too Big Reply Flood",
  "ICMP Destination Unreachable Flood",
  "ICMP Echo Reply Flood",
  "ICMP Echo Request Flood",
  "ICMP Flood",
  "ICMP Flood Attack",
  "ICMP Netmask Reply Flood",
  "ICMP Netmask Request Flood",
  "ICMP Redirect Flood",
  "ICMP Redirect Reply Flood",
  "ICMP Router Advertisement Flood",
  "ICMP Router Advertisement Reply Flood",
  "ICMP Router Discovery Flood",
  "ICMP Router Discovery Reply Flood",
  "ICMP Router Solicitation Flood",
  "ICMP Router Solicitation Reply Flood",
  "ICMP Source Quench Flood",
  "ICMP Source Quench Reply Flood",
  "ICMP Timestamp Reply Flood",
  "ICMP Timestamp Request Flood",
  "IKE Exploitation",
  "IP Fragmentation Attack",
  "IP Header Manipulation",
  "IP Spoofing",
  "IPFS Node Exploit",
  "IPsec Authentication Downgrade",
  "IPsec Cipher Downgrade",
  "IPsec DoS Attack",
  "IPsec Encryption Downgrade",
  "IPsec Exploitation",
  "IPsec Key Exchange Manipulation",
  "IPsec NAT Traversal Exploitation",
  "IPsec Protocol Downgrade",
  "IPsec Reassembly Attack",
  "IPsec Replay Attack",
  "IPsec Security Association Hijacking",
  "IPsec Spoofing",
  "IPsec Tunnel Interface Exploitation",
  "Immersive Technology Malware",
  "Impersonation Attack",
  "Industrial Control System (ICS) Attack",
  "Industrial IoT Exploit",
  "Influence Campaign",
  "Information Gathering",
  "Initial Coin Offering (ICO) Fraud",
  "Insecure Direct Object References (IDOR)",
  "Insider Privilege Escalation",
  "Insider Threat",
  "Insider Threat in DeFi Platform",
  "Insufficient Logging & Monitoring",
  "Integer Overflow",
  "Interactive Kiosk Malware",
  "IoT Botnet Recruitment",
  "IoT DDoS",
  "IoT Device 5G Exploit",
  "IoT Device Actuator Exploit",
  "IoT Device Automotive System Exploit",
  "IoT Device Autonomous System Exploit",
  "IoT Device Blockchain Integration Exploit",
  "IoT Device Bluetooth Exploit",
  "IoT Device Building Management System Exploit",
  "IoT Device Cloud Integration Exploit",
  "IoT Device Control System Exploit",
  "IoT Device Data Analytics Exploit",
  "IoT Device Data Availability Exploit",
  "IoT Device Data Integrity Exploit",
  "IoT Device Data Privacy Exploit",
  "IoT Device Decentralized Network Exploit",
  "IoT Device Default Password Exploit",
  "IoT Device Edge Computing Exploit",
  "IoT Device Electric Vehicle Charging Station Exploit",
  "IoT Device Energy Management System Exploit",
  "IoT Device Exploitation",
  "IoT Device Firmware Exploit",
  "IoT Device Firmware Update Bypass",
  "IoT Device Hardcoded Credentials Exploit",
  "IoT Device Healthcare Device Exploit",
  "IoT Device Industrial Control System Exploit",
  "IoT Device LTE Exploit",
  "IoT Device LoRaWAN Exploit",
  "IoT Device Machine Learning Exploit",
  "IoT Device Medical Device Exploit",
  "IoT Device Mesh Network Exploit",
  "IoT Device NB-IoT Exploit",
  "IoT Device Network Exploit",
  "IoT Device Over-the-Air (OTA) Update Exploit",
  "IoT Device Physical Tampering",
  "IoT Device Renewable Energy System Exploit",
  "IoT Device SCADA System Exploit",
  "IoT Device Sensor Manipulation",
  "IoT Device Sigfox Exploit",
  "IoT Device Smart Air Conditioner Exploit",
  "IoT Device Smart City Infrastructure Exploit",
  "IoT Device Smart Coffee Maker Exploit",
  "IoT Device Smart Dishwasher Exploit",
  "IoT Device Smart Door Lock Exploit",
  "IoT Device Smart Garden Exploit",
  "IoT Device Smart Grid Exploit",
  "IoT Device Smart Heater Exploit",
  "IoT Device Smart Home Exploit",
  "IoT Device Smart Light Bulb Exploit",
  "IoT Device Smart Lighting System Exploit",
  "IoT Device Smart Meter Exploit",
  "IoT Device Smart Mirror Exploit",
  "IoT Device Smart Oven Exploit",
  "IoT Device Smart Pet Activity Analytics Exploit",
  "IoT Device Smart Pet Activity Monitoring Plan Exploit",
  "IoT Device Smart Pet Activity Reporting Exploit",
  "IoT Device Smart Pet Activity Tracking Exploit",
  "IoT Device Smart Pet Adoption Exploit",
  "IoT Device Smart Pet Behavior Analysis Exploit",
  "IoT Device Smart Pet Behavior Analytics Exploit",
  "IoT Device Smart Pet Behavior Monitoring Plan Exploit",
  "IoT Device Smart Pet Behavior Plan Exploit",
  "IoT Device Smart Pet Behavior Reporting Exploit",
  "IoT Device Smart Pet Breeding Exploit",
  "IoT Device Smart Pet Camera Exploit",
  "IoT Device Smart Pet Collar Exploit",
  "IoT Device Smart Pet Emergency Alert Exploit",
  "IoT Device Smart Pet Emergency Plan Exploit",
  "IoT Device Smart Pet Entertainment Exploit",
  "IoT Device Smart Pet Exercise Analytics Exploit",
  "IoT Device Smart Pet Exercise Monitoring Plan Exploit",
  "IoT Device Smart Pet Exercise Plan Exploit",
  "IoT Device Smart Pet Exercise Reporting Exploit",
  "IoT Device Smart Pet Feeder Exploit",
  "IoT Device Smart Pet Genetic Exploit",
  "IoT Device Smart Pet Groomer Exploit",
  "IoT Device Smart Pet Health Analytics Exploit",
  "IoT Device Smart Pet Health Insurance Exploit",
  "IoT Device Smart Pet Health Monitor Exploit",
  "IoT Device Smart Pet Health Monitoring Plan Exploit",
  "IoT Device Smart Pet Health Plan Exploit",
  "IoT Device Smart Pet Health Reporting Exploit",
  "IoT Device Smart Pet Insurance Exploit",
  "IoT Device Smart Pet Liability Insurance Exploit",
  "IoT Device Smart Pet Life Insurance Exploit",
  "IoT Device Smart Pet Lost Tracking Exploit",
  "IoT Device Smart Pet Medical Alert Exploit",
  "IoT Device Smart Pet Medical Plan Exploit",
  "IoT Device Smart Pet Nutrition Analytics Exploit",
  "IoT Device Smart Pet Nutrition Exploit",
  "IoT Device Smart Pet Nutrition Monitoring Plan Exploit",
  "IoT Device Smart Pet Nutrition Plan Exploit",
  "IoT Device Smart Pet Nutrition Reporting Exploit",
  "IoT Device Smart Pet Owner Exploit",
  "IoT Device Smart Pet Property Insurance Exploit",
  "IoT Device Smart Pet Sitter Exploit",
  "IoT Device Smart Pet Stress Analytics Exploit",
  "IoT Device Smart Pet Stress Detection Exploit",
  "IoT Device Smart Pet Stress Monitoring Plan Exploit",
  "IoT Device Smart Pet Stress Reporting Exploit",
  "IoT Device Smart Pet Supply Store Exploit",
  "IoT Device Smart Pet Tracker Exploit",
  "IoT Device Smart Pet Trainer Exploit",
  "IoT Device Smart Pet Training Exploit",
  "IoT Device Smart Pet Travel Insurance Exploit",
  "IoT Device Smart Pet Vaccination Plan Exploit",
  "IoT Device Smart Pet Vaccination Tracking Exploit",
  "IoT Device Smart Pet Veterinarian Exploit",
  "IoT Device Smart Pet Wellness Analytics Exploit",
  "IoT Device Smart Pet Wellness Monitoring Exploit",
  "IoT Device Smart Pet Wellness Monitoring Plan Exploit",
  "IoT Device Smart Pet Wellness Plan Exploit",
  "IoT Device Smart Pet Wellness Reporting Exploit",
  "IoT Device Smart Plug Exploit",
  "IoT Device Smart Refrigerator Exploit",
  "IoT Device Smart Robot Exploit",
  "IoT Device Smart Security System Exploit",
  "IoT Device Smart Speaker Exploit",
  "IoT Device Smart Surveillance Camera Exploit",
  "IoT Device Smart TV Exploit",
  "IoT Device Smart Thermostat Exploit",
  "IoT Device Smart Traffic System Exploit",
  "IoT Device Smart Vacuum Cleaner Exploit",
  "IoT Device Smart Washing Machine Exploit",
  "IoT Device Smart Water Heater Exploit",
  "IoT Device Supply Chain Exploit",
  "IoT Device Transportation System Exploit",
  "IoT Device Unauthorized Access Exploit",
  "IoT Device Wi-Fi Exploit",
  "IoT Device Wireless Protocol Exploit",
  "IoT Device Z-Wave Exploit",
  "IoT Device Zigbee Exploit",
  "IoT Firmware Exploit",
  "IoT Mesh Network Exploit",
  "JOP Chain Construction",
  "JSON Hijacking",
  "JSON Injection",
  "JWT Exploitation",
  "Jump-Oriented Programming (JOP)",
  "Kerberoasting",
  "Keylogger Deployment",
  "Keylogging",
  "Known Vulnerability Exploitation",
  "Kubernetes Cluster Exploit",
  "LDAP Injection",
  "LSASS Memory Extraction",
  "Land Attack",
  "Lateral Movement",
  "Local File Inclusion (LFI)",
  "Logic Bomb",
  "Logic Bomb Deployment",
  "Logjam Attack",
  "Loopback Attack",
  "Lucky Thirteen Attack",
  "MAC Spoofing",
  "Machine Learning Model Poisoning",
  "Malicious Browser Extensions",
  "Malicious Mobile Apps",
  "Malicious USB Devices",
  "Malvertising",
  "Malware",
  "Malware Encryption",
  "Man-in-the-Browser (MitB)",
  "Man-in-the-Middle (MITM) Attack",
  "Man-in-the-Middle (MitM)",
  "Man-in-the-Mobile (MitMo)",
  "Medical Device Exploit",
  "Meltdown Attack",
  "Meltdown Variant",
  "Meltdown-BR Attack",
  "Meltdown-BR Variant A",
  "Meltdown-BR Variant B",
  "Meltdown-PK Attack",
  "Meltdown-PK Variant A",
  "Meltdown-PK Variant B",
  "Meltdown-PR Attack",
  "Meltdown-PR Variant A",
  "Meltdown-PR Variant B",
  "Meltdown-UG Attack",
  "Meltdown-UG Variant A",
  "Meltdown-UG Variant B",
  "Memcached Amplification",
  "Microcontroller Exploitation",
  "Microphone Hijacking",
  "Mimikatz Attack",
  "Mixed Reality (MR) Device Exploit",
  "Multi-Cloud Resource Exploitation",
  "Multi-Factor Authentication Bypass",
  "NFC Exploitation",
  "NFT Marketplace Exploit",
  "NTDS.dit Extraction",
  "NTP Amplification",
  "NXDOMAIN Attack",
  "Network Spoofing",
  "Network Time Protocol (NTP) Amplification",
  "NoSQL Injection",
  "OAuth Misuse",
  "Open Redirect Attack",
  "Optical Side-Channel",
  "PLC Hacking",
  "POODLE Attack",
  "Pass-the-Hash",
  "Pass-the-Ticket",
  "Password Spraying",
  "Path Traversal",
  "Persistence",
  "Phantom Load",
  "Pharming",
  "Phishing",
  "Ping Flood Attack",
  "Ping of Death",
  "Pivoting",
  "Point of Sale (POS) Malware",
  "Post-Exploitation",
  "Post-Quantum Cryptography Attack",
  "Power Analysis Attack",
  "Pretexting",
  "Privilege Escalation",
  "Programmable Logic Controller (PLC) Exploit",
  "Protocol Attack",
  "Psychological Manipulation",
  "QR Code Phishing",
  "Quantum Algorithm Exploit",
  "Quantum Bit Flip Attack",
  "Quantum Channel Exploit",
  "Quantum Coherence Attack",
  "Quantum Computing Side-Channel Attack",
  "Quantum Cryptanalysis Attack",
  "Quantum Entanglement Exploit",
  "Quantum Entanglement Swapping Attack",
  "Quantum Error Correction Exploit",
  "Quantum Key Distribution (QKD) Exploit",
  "Quantum Key Escrow Exploit",
  "Quantum Key Refresh Attack",
  "Quantum Key Reuse Attack",
  "Quantum Measurement Exploit",
  "Quantum Memory Exploit",
  "Quantum Network Exploit",
  "Quantum No-Cloning Attack",
  "Quantum Noise Exploit",
  "Quantum Phase Flip Attack",
  "Quantum Random Number Generator Exploit",
  "Quantum Repeater Exploit",
  "Quantum Secure Direct Communication Attack",
  "Quantum Superposition Attack",
  "Quantum Supremacy Attack",
  "Quantum Teleportation Attack",
  "Quantum Teleportation Exploit",
  "Quantum-based Authentication Exploit",
  "Quantum-based Authorization Exploit",
  "Quantum-based Data Accessibility Exploit",
  "Quantum-based Data Aggregation Exploit",
  "Quantum-based Data Analysis Exploit",
  "Quantum-based Data Annotation Exploit",
  "Quantum-based Data Anonymization Exploit",
  "Quantum-based Data Archiving Exploit",
  "Quantum-based Data Authenticity Exploit",
  "Quantum-based Data Availability Exploit",
  "Quantum-based Data Backup Exploit",
  "Quantum-based Data Business Continuity Exploit",
  "Quantum-based Data Classification Exploit",
  "Quantum-based Data Compliance Exploit",
  "Quantum-based Data Confidentiality Exploit",
  "Quantum-based Data Consensus Exploit",
  "Quantum-based Data Consistency Exploit",
  "Quantum-based Data Context Exploit",
  "Quantum-based Data Dashboards Exploit",
  "Quantum-based Data Destruction Exploit",
  "Quantum-based Data Disaster Recovery Exploit",
  "Quantum-based Data Disposal Exploit",
  "Quantum-based Data Ecosystem Exploit",
  "Quantum-based Data Fabric Exploit",
  "Quantum-based Data Fault Tolerance Exploit",
  "Quantum-based Data Filtering Exploit",
  "Quantum-based Data Freshness Exploit",
  "Quantum-based Data Generation Exploit",
  "Quantum-based Data Governance Exploit",
  "Quantum-based Data Granularity Exploit",
  "Quantum-based Data Hiding Exploit",
  "Quantum-based Data High Availability Exploit",
  "Quantum-based Data Incident Response Exploit",
  "Quantum-based Data Indexing Exploit",
  "Quantum-based Data Integration Exploit",
  "Quantum-based Data Integrity Exploit",
  "Quantum-based Data Intent Exploit",
  "Quantum-based Data Interoperability Exploit",
  "Quantum-based Data Knowledge Graph Exploit",
  "Quantum-based Data Labeling Exploit",
  "Quantum-based Data Lakes Exploit",
  "Quantum-based Data Load Balancing Exploit",
  "Quantum-based Data Manipulation Exploit",
  "Quantum-based Data Meaning Exploit",
  "Quantum-based Data Mesh Exploit",
  "Quantum-based Data Migration Exploit",
  "Quantum-based Data Mining Exploit",
  "Quantum-based Data Models Exploit",
  "Quantum-based Data Ontology Exploit",
  "Quantum-based Data Partitioning Exploit",
  "Quantum-based Data Pipelines Exploit",
  "Quantum-based Data Portability Exploit",
  "Quantum-based Data Pragmatics Exploit",
  "Quantum-based Data Privacy Exploit",
  "Quantum-based Data Processing Exploit",
  "Quantum-based Data Pseudonymization Exploit",
  "Quantum-based Data Purging Exploit",
  "Quantum-based Data Recovery Exploit",
  "Quantum-based Data Redundancy Exploit",
  "Quantum-based Data Reliability Exploit",
  "Quantum-based Data Replication Exploit",
  "Quantum-based Data Reporting Exploit",
  "Quantum-based Data Retention Exploit",
  "Quantum-based Data Risk Assessment Exploit",
  "Quantum-based Data Sampling Exploit",
  "Quantum-based Data Schema Exploit",
  "Quantum-based Data Security Alerting Exploit",
  "Quantum-based Data Security Attack Vector",
  "Quantum-based Data Security Audit Exploit",
  "Quantum-based Data Security Breach Exploit",
  "Quantum-based Data Security Compliance Exploit",
  "Quantum-based Data Security Control Exploit",
  "Quantum-based Data Security Detection Exploit",
  "Quantum-based Data Security Exploit Adware",
  "Quantum-based Data Security Exploit Backdoor",
  "Quantum-based Data Security Exploit Botnet",
  "Quantum-based Data Security Exploit Chain",
  "Quantum-based Data Security Exploit Cryptominer",
  "Quantum-based Data Security Exploit Data Stealer",
  "Quantum-based Data Security Exploit Deliverable",
  "Quantum-based Data Security Exploit Downloader",
  "Quantum-based Data Security Exploit Dropper",
  "Quantum-based Data Security Exploit Exploit Anti-Analysis Exploit",
  "Quantum-based Data Security Exploit Exploit Chain Loader",
  "Quantum-based Data Security Exploit Exploit Command and Control",
  "Quantum-based Data Security Exploit Exploit Covering Tracks",
  "Quantum-based Data Security Exploit Exploit Data Exfiltration",
  "Quantum-based Data Security Exploit Exploit Delivery Exploit",
  "Quantum-based Data Security Exploit Exploit Detection Bypass",
  "Quantum-based Data Security Exploit Exploit Encryption Exploit",
  "Quantum-based Data Security Exploit Exploit Evasion Exploit",
  "Quantum-based Data Security Exploit Exploit Kit Loader",
  "Quantum-based Data Security Exploit Exploit Lateral Movement",
  "Quantum-based Data Security Exploit Exploit Log Manipulation",
  "Quantum-based Data Security Exploit Exploit Metamorphism Exploit",
  "Quantum-based Data Security Exploit Exploit Obfuscation Exploit",
  "Quantum-based Data Security Exploit Exploit Packing Exploit",
  "Quantum-based Data Security Exploit Exploit Payload Delivery",
  "Quantum-based Data Security Exploit Exploit Persistence",
  "Quantum-based Data Security Exploit Exploit Polymorphism Exploit",
  "Quantum-based Data Security Exploit Exploit Privilege Escalation",
  "Quantum-based Data Security Exploit Exploit Signature",
  "Quantum-based Data Security Exploit Exploit Stealth Exploit",
  "Quantum-based Data Security Exploit Exploit Technique",
  "Quantum-based Data Security Exploit Exploit Variant",
  "Quantum-based Data Security Exploit Framework",
  "Quantum-based Data Security Exploit Keylogger",
  "Quantum-based Data Security Exploit Kit",
  "Quantum-based Data Security Exploit Malware",
  "Quantum-based Data Security Exploit Payload",
  "Quantum-based Data Security Exploit Ransomware",
  "Quantum-based Data Security Exploit Rootkit",
  "Quantum-based Data Security Exploit Script",
  "Quantum-based Data Security Exploit Spyware",
  "Quantum-based Data Security Exploit Tool",
  "Quantum-based Data Security Exploit Trojan",
  "Quantum-based Data Security Exploit Virus",
  "Quantum-based Data Security Exploit Worm",
  "Quantum-based Data Security Framework Exploit",
  "Quantum-based Data Security Incident Exploit",
  "Quantum-based Data Security Mitigation Exploit",
  "Quantum-based Data Security Monitoring Exploit",
  "Quantum-based Data Security Policy Exploit",
  "Quantum-based Data Security Prevention Exploit",
  "Quantum-based Data Security Response Exploit",
  "Quantum-based Data Security Standard Exploit",
  "Quantum-based Data Segregation Exploit",
  "Quantum-based Data Semantics Exploit",
  "Quantum-based Data Sharding Exploit",
  "Quantum-based Data Sorting Exploit",
  "Quantum-based Data Streams Exploit",
  "Quantum-based Data Structure Exploit",
  "Quantum-based Data Summarization Exploit",
  "Quantum-based Data Synchronization Exploit",
  "Quantum-based Data Syntax Exploit",
  "Quantum-based Data Synthesis Exploit",
  "Quantum-based Data Tagging Exploit",
  "Quantum-based Data Taxonomy Exploit",
  "Quantum-based Data Threat Intelligence Exploit",
  "Quantum-based Data Transformation Exploit",
  "Quantum-based Data Usability Exploit",
  "Quantum-based Data Validity Exploit",
  "Quantum-based Data Visualization Exploit",
  "Quantum-based Data Warehouses Exploit",
  "Quantum-based Decryption Exploit",
  "Quantum-based Encryption Exploit",
  "Quantum-based Signature Exploit",
  "Quantum-based Steganography Exploit",
  "Quantum-resistant Algorithm Exploit",
  "Quid Pro Quo",
  "RFID Skimming",
  "ROBOT Attack",
  "ROP Chain Construction",
  "Race Condition",
  "Race Condition Exploit",
  "Radio Frequency Jamming",
  "Rainbow Table Attack",
  "Ransomware",
  "Ransomware Deployment",
  "Reconnaissance",
  "Reflection Attack",
  "Remote Code Execution",
  "Remote Desktop Protocol (RDP) Exploit",
  "Remote File Inclusion (RFI)",
  "Renewable Energy System Exploit",
  "Replay Attack",
  "Resource Exhaustion",
  "Return-Oriented Programming (ROP)",
  "Return-to-libc Attack",
  "Reverse Shell Deployment",
  "Rogue Access Points",
  "Rootkit",
  "Rootkit Installation",
  "Route Flapping",
  "Routing Protocol Exploit",
  "Routing Table Poisoning",
  "Rowhammer Attack",
  "SAM Database Extraction",
  "SCADA System Exploitation",
  "SDN Controller Exploit",
  "SMB Relay Attack",
  "SQL Injection",
  "SSDP Amplification",
  "SSL Certificate Chain Manipulation",
  "SSL Certificate Forgery",
  "SSL Certificate Pinning Bypass",
  "SSL Certificate Revocation Bypass",
  "SSL Cipher Suite Downgrade",
  "SSL Renegotiation Attack",
  "SSL Renegotiation DoS",
  "SSL Session Hijacking",
  "SSL Session Resumption Attack",
  "SSL Stripping",
  "SSL Version Downgrade",
  "SSL/TLS Exploitation",
  "SSL/TLS Padding Oracle Attack",
  "SSL/TLS RC4 Bias Attack",
  "SSL/TLS RC4 Bias Vulnerability",
  "SSL/TLS RC4 Cipher Attack",
  "SSL/TLS RC4 Cipher Vulnerability",
  "SSL/TLS RC4 Collision Attack",
  "SSL/TLS RC4 Collision Vulnerability",
  "SSL/TLS RC4 Exploitation",
  "SSL/TLS RC4 Key Attack",
  "SSL/TLS RC4 Key Vulnerability",
  "SSL/TLS RC4 MAC Attack",
  "SSL/TLS RC4 MAC Vulnerability",
  "SSL/TLS RC4 RC4 Bias",
  "SSL/TLS RC4 RC4 Cipher",
  "SSL/TLS RC4 RC4 Cipher Suite",
  "SSL/TLS RC4 RC4 Cipher Suite Attack",
  "SSL/TLS RC4 RC4 Cipher Suite Breach",
  "SSL/TLS RC4 RC4 Cipher Suite Break",
  "SSL/TLS RC4 RC4 Cipher Suite DoS",
  "SSL/TLS RC4 RC4 Cipher Suite Downgrade",
  "SSL/TLS RC4 RC4 Cipher Suite Exploit",
  "SSL/TLS RC4 RC4 Cipher Suite Exploitation",
  "SSL/TLS RC4 RC4 Cipher Suite Hack",
  "SSL/TLS RC4 RC4 Cipher Suite Penetration",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerability",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerability Exploit",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Attack",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Breach",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Break",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable DoS",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Exploit",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Exploitation",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Hack",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Penetration",
  "SSL/TLS RC4 RC4 Cipher Suite Vulnerable Vulnerability",
  "SSL/TLS RC4 RC4 Collision",
  "SSL/TLS RC4 RC4 Exploitation",
  "SSL/TLS RC4 RC4 Key",
  "SSL/TLS RC4 RC4 MAC",
  "SSL/TLS RC4 RC4 Replay",
  "SSL/TLS RC4 RC4 Session",
  "SSL/TLS RC4 RC4 Stream",
  "SSL/TLS RC4 RC4 Vulnerability",
  "SSL/TLS RC4 Replay Attack",
  "SSL/TLS RC4 Replay Vulnerability",
  "SSL/TLS RC4 Session Vulnerability",
  "SSL/TLS RC4 Stream Attack",
  "SSL/TLS RC4 Stream Vulnerability",
  "SSL/TLS RC4 Vulnerability Exploitation",
  "SYN Flood",
  "Scanning",
  "Security Misconfiguration",
  "Self-Service Kiosk Exploit",
  "Sensitive Data Exposure",
  "Sensor Tampering",
  "Server-Side Request Forgery (SSRF)",
  "Serverless Function Code Injection",
  "Serverless Function Exploitation",
  "Service Account Abuse",
  "Service Mesh Data Interception",
  "Session Fixation",
  "Session Hijacking",
  "Shoulder Surfing",
  "Sia Storage Exploit",
  "Side-Channel Attack",
  "Side-Channel Timing",
  "Sidejacking",
  "Silver Ticket Attack",
  "Silver Ticket Forgery",
  "Simple Power Analysis (SPA)",
  "Skimming Attack",
  "Slowloris",
  "Smart Air Conditioner Exploit",
  "Smart Air Purifier Exploit",
  "Smart Alarm System Exploit",
  "Smart Appliance Malware",
  "Smart Aquarium Controller Exploit",
  "Smart Beehive Exploit",
  "Smart Bird Cage Exploit",
  "Smart Ceiling Fan Exploit",
  "Smart Chicken Coop Exploit",
  "Smart City Infrastructure Exploit",
  "Smart Clothing Malware",
  "Smart Coffee Maker Exploit",
  "Smart Contract Dependency Attack",
  "Smart Contract Exploit",
  "Smart Contract Logic Exploit",
  "Smart Contract Overflow",
  "Smart Contract Proxy Exploit",
  "Smart Contract Reentrancy Attack",
  "Smart Contract Replay Attack",
  "Smart Contract Underflow",
  "Smart Contract Upgradability Exploit",
  "Smart Device Hijacking",
  "Smart Dishwasher Exploit",
  "Smart Door Lock Exploit",
  "Smart Doorbell Exploit",
  "Smart Dryer Exploit",
  "Smart Fence Exploit",
  "Smart Fish Tank Exploit",
  "Smart Garage Door Exploit",
  "Smart Garden System Exploit",
  "Smart Gate Exploit",
  "Smart Glasses Exploit",
  "Smart Grid Attack",
  "Smart Grid Data Tampering",
  "Smart HVAC System Exploit",
  "Smart Hammam Exploit",
  "Smart Heater Exploit",
  "Smart Helmets Malware",
  "Smart Home Device Attack",
  "Smart Home Hub Exploit",
  "Smart Hot Tub Exploit",
  "Smart Irrigation System Exploit",
  "Smart Jewelry Exploit",
  "Smart Lawn Sprinkler Exploit",
  "Smart Light Bulb Exploit",
  "Smart Light Switch Exploit",
  "Smart Lighting System Exploit",
  "Smart Lock Exploit",
  "Smart Meter Firmware Exploit",
  "Smart Meter Tampering",
  "Smart Mirror Exploit",
  "Smart Office Device Exploit",
  "Smart Oven Exploit",
  "Smart Pet Activity Analytics Exploit",
  "Smart Pet Activity Dashboard Exploit",
  "Smart Pet Activity Monitoring Plan Exploit",
  "Smart Pet Activity Reporting Exploit",
  "Smart Pet Activity Tracking Exploit",
  "Smart Pet Activity Visualization Exploit",
  "Smart Pet Adoption Exploit",
  "Smart Pet Air Quality Exploit",
  "Smart Pet Behavior Analytics Exploit",
  "Smart Pet Behavior Dashboard Exploit",
  "Smart Pet Behavior Modification Exploit",
  "Smart Pet Behavior Monitoring Plan Exploit",
  "Smart Pet Behavior Plan Exploit",
  "Smart Pet Behavior Reporting Exploit",
  "Smart Pet Behavior Visualization Exploit",
  "Smart Pet Behavioral Analysis Exploit",
  "Smart Pet Breed Exploit",
  "Smart Pet Breeding Exploit",
  "Smart Pet Camera Exploit",
  "Smart Pet Cleaning System Exploit",
  "Smart Pet Collar Exploit",
  "Smart Pet Comfort System Exploit",
  "Smart Pet Communication Exploit",
  "Smart Pet Diet Control Exploit",
  "Smart Pet Disability Insurance Exploit",
  "Smart Pet Drinking System Exploit",
  "Smart Pet Emergency Alert Exploit",
  "Smart Pet Emergency Plan Exploit",
  "Smart Pet Emotion Recognition Exploit",
  "Smart Pet Enclosure Exploit",
  "Smart Pet Entertainment System Exploit",
  "Smart Pet Exercise Analytics Exploit",
  "Smart Pet Exercise Dashboard Exploit",
  "Smart Pet Exercise Monitoring Plan Exploit",
  "Smart Pet Exercise Plan Exploit",
  "Smart Pet Exercise Reporting Exploit",
  "Smart Pet Exercise Scheduling Exploit",
  "Smart Pet Exercise System Exploit",
  "Smart Pet Exercise Visualization Exploit",
  "Smart Pet Feed Monitoring Exploit",
  "Smart Pet Feeder Exploit",
  "Smart Pet Feeding System Exploit",
  "Smart Pet Genetic Exploit",
  "Smart Pet Groomer Exploit",
  "Smart Pet Grooming System Exploit",
  "Smart Pet Habitat Exploit",
  "Smart Pet Health Analytics Exploit",
  "Smart Pet Health Dashboard Exploit",
  "Smart Pet Health Diagnosis Exploit",
  "Smart Pet Health Insurance Exploit",
  "Smart Pet Health Monitor Exploit",
  "Smart Pet Health Monitoring Plan Exploit",
  "Smart Pet Health Plan Exploit",
  "Smart Pet Health Reporting Exploit",
  "Smart Pet Health Tracking Exploit",
  "Smart Pet Health Visualization Exploit",
  "Smart Pet Humidity Control Exploit",
  "Smart Pet Insurance Exploit",
  "Smart Pet Interaction System Exploit",
  "Smart Pet Liability Insurance Exploit",
  "Smart Pet Life Insurance Exploit",
  "Smart Pet Light Control Exploit",
  "Smart Pet Litter Box Exploit",
  "Smart Pet Lost Pet Tracking Exploit",
  "Smart Pet Medical Alert Exploit",
  "Smart Pet Medical Plan Exploit",
  "Smart Pet Noise Control Exploit",
  "Smart Pet Nutrition Analytics Exploit",
  "Smart Pet Nutrition Dashboard Exploit",
  "Smart Pet Nutrition Exploit",
  "Smart Pet Nutrition Monitoring Plan Exploit",
  "Smart Pet Nutrition Plan Exploit",
  "Smart Pet Nutrition Planning Exploit",
  "Smart Pet Nutrition Reporting Exploit",
  "Smart Pet Nutrition Visualization Exploit",
  "Smart Pet Owner Exploit",
  "Smart Pet Playtime Exploit",
  "Smart Pet Property Insurance Exploit",
  "Smart Pet Punishment System Exploit",
  "Smart Pet Reward System Exploit",
  "Smart Pet Shop Exploit",
  "Smart Pet Sitter Exploit",
  "Smart Pet Socialization Exploit",
  "Smart Pet Species Exploit",
  "Smart Pet Storage System Exploit",
  "Smart Pet Stress Analytics Exploit",
  "Smart Pet Stress Dashboard Exploit",
  "Smart Pet Stress Detection Exploit",
  "Smart Pet Stress Monitoring Plan Exploit",
  "Smart Pet Stress Reporting Exploit",
  "Smart Pet Stress Visualization Exploit",
  "Smart Pet Supply Store Exploit",
  "Smart Pet Temperature Control Exploit",
  "Smart Pet Tracker Exploit",
  "Smart Pet Trainer Exploit",
  "Smart Pet Training Scheduling Exploit",
  "Smart Pet Training System Exploit",
  "Smart Pet Travel Insurance Exploit",
  "Smart Pet Treatment Recommendation Exploit",
  "Smart Pet Vaccination Plan Exploit",
  "Smart Pet Vaccination Tracking Exploit",
  "Smart Pet Veterinarian Exploit",
  "Smart Pet Waste Management Exploit",
  "Smart Pet Water Quality Exploit",
  "Smart Pet Wellness Analytics Exploit",
  "Smart Pet Wellness Dashboard Exploit",
  "Smart Pet Wellness Monitoring Exploit",
  "Smart Pet Wellness Monitoring Plan Exploit",
  "Smart Pet Wellness Plan Exploit",
  "Smart Pet Wellness Reporting Exploit",
  "Smart Pet Wellness Visualization Exploit",
  "Smart Plug Exploit",
  "Smart Pool Controller Exploit",
  "Smart Refrigerator Exploit",
  "Smart Rings Malware",
  "Smart Robot Exploit",
  "Smart Sauna Exploit",
  "Smart Security Camera Exploit",
  "Smart Smoke Alarm Exploit",
  "Smart Smoke Detector Exploit",
  "Smart Spa Controller Exploit",
  "Smart Speaker Exploit",
  "Smart TV Exploit",
  "Smart Terrarium Controller Exploit",
  "Smart Textiles Exploit",
  "Smart Thermostat Exploit",
  "Smart Toaster Exploit",
  "Smart Traffic System Exploit",
  "Smart Vacuum Cleaner Exploit",
  "Smart Vehicle Hacking",
  "Smart Washer/Dryer Exploit",
  "Smart Washing Machine Exploit",
  "Smart Watches Exploit",
  "Smart Water Heater Exploit",
  "Smart Water Valve Exploit",
  "Smishing",
  "Smurf Attack",
  "Social Engineering",
  "Social Media Takeover",
  "Software-Defined Networking (SDN) Exploit",
  "Spear Phishing",
  "Spectre Attack",
  "Spectre Variant 1",
  "Spectre Variant 2",
  "Spectre-BTB Attack",
  "Spectre-BTB-V1",
  "Spectre-BTB-V1 Variant A",
  "Spectre-BTB-V1 Variant B",
  "Spectre-BTB-V2",
  "Spectre-BTB-V2 Variant A",
  "Spectre-BTB-V2 Variant B",
  "Spectre-BTB-V3",
  "Spectre-BTB-V3 Variant A",
  "Spectre-BTB-V3 Variant B",
  "Spectre-STL Attack",
  "Spectre-STL-V1",
  "Spectre-STL-V1 Variant A",
  "Spectre-STL-V1 Variant B",
  "Spectre-STL-V2",
  "Spectre-STL-V2 Variant A",
  "Spectre-STL-V2 Variant B",
  "Spectre-STL-V3",
  "Spectre-STL-V3 Variant A",
  "Spectre-STL-V3 Variant B",
  "Spectre-V1",
  "Spectre-V1 Variant A",
  "Spectre-V1 Variant B",
  "Spectre-V2",
  "Spectre-V2 Variant A",
  "Spectre-V2 Variant B",
  "SpectreRSB Attack",
  "SpectreRSB-V1",
  "SpectreRSB-V1 Variant A",
  "SpectreRSB-V1 Variant B",
  "SpectreRSB-V2",
  "SpectreRSB-V2 Variant A",
  "SpectreRSB-V2 Variant B",
  "SpectreRSB-V3",
  "SpectreRSB-V3 Variant A",
  "SpectreRSB-V3 Variant B",
  "Speculative Execution Attack",
  "Spyware",
  "Spyware Installation",
  "Stablecoin Attack",
  "Stack Overflow",
  "Storj Storage Exploit",
  "Supply Chain Attack",
  "Supply Chain Compromise",
  "Swarm Storage Exploit",
  "Synthetic Asset Exploit",
  "TCP Hijacking",
  "TCP Reset Attack",
  "TCP Sequence Prediction",
  "TLS Certificate Chain Manipulation",
  "TLS Certificate Forgery",
  "TLS Certificate Pinning Bypass",
  "TLS Certificate Revocation Bypass",
  "TLS Cipher Suite Downgrade",
  "TLS Renegotiation Attack",
  "TLS Renegotiation DoS",
  "TLS Session Hijacking",
  "TLS Session Resumption Attack",
  "TLS Version Downgrade",
  "Tailgating",
  "Teardrop Attack",
  "Telehealth Platform Exploit",
  "Telehealth System Attack",
  "Telematics Gateway Exploit",
  "Telematics System Exploit",
  "Template Injection",
  "Ticket Granting Ticket (TGT) Attack",
  "Time Bomb",
  "Timing Attack",
  "Token Sale Exploit",
  "Trojan Horse",
  "UDP Flood",
  "UDP Flood Attack",
  "URL Spoofing",
  "Unified Communications Exploit",
  "Unvalidated Redirects and Forwards",
  "Urban IoT Device Exploit",
  "Vehicular Ad-hoc Network (VANET) Attack",
  "Video Conferencing Malware",
  "Virtual Reality (VR) Device Exploit",
  "Virtualization Escape",
  "Virus",
  "Vishing",
  "Voice Assistant Malware",
  "Volume-Based Attack",
  "Vulnerability Exploitation",
  "Watering Hole Attack",
  "Wearable Device Exploitation",
  "Wearable Device Malware",
  "Webcam Hijacking",
  "Whaling",
  "Wi-Fi Eavesdropping",
  "Wi-Fi Jamming",
  "Wireless Sniffing",
  "Worm",
  "XML External Entity (XXE) Attack",
  "XML Injection",
  "Zero-Day Cloud Function Exploit",
  "Zero-Day Exploit",
  "Zero-Day Exploit in DeFi Protocol",
  "Zero-Day Vulnerability",
  "Zero-Day Vulnerability Exploit",
  "ZombieLoad Attack",
  "ZombieLoad Variant",
  "ZombieLoad-V1 Attack",
  "ZombieLoad-V1 Variant A",
  "ZombieLoad-V1 Variant B",
  "ZombieLoad-V2 Attack",
  "ZombieLoad-V2 Variant A",
  "ZombieLoad-V2 Variant B",
  "ZombieLoad-V3 Attack",
  "ZombieLoad-V3 Variant A",
  "ZombieLoad-V3 Variant B"
];


